import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('configure milestones, report partial payments, confirm and reverse on desktop/mobile',async({page,context})=>{
 const f=JSON.parse(await readFile('.local/payments-test-project.json','utf8')) as {projectId:string;quoteId:string};
 if(process.env.MOBLUX_TEST_API_ORIGIN)await context.route('**/api/**',async r=>{const u=new URL(r.request().url());const response=await r.fetch({url:process.env.MOBLUX_TEST_API_ORIGIN+u.pathname+u.search});await r.fulfill({response});});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/login');await page.getByLabel('Development access code').fill(process.env.DEV_LOGIN_CODE!);await page.getByRole('button',{name:'Open workspace'}).click();await expect(page.getByRole('heading',{name:'Make room for good work.'})).toBeVisible();await page.goto(`/projects/${f.projectId}`);await page.getByRole('tab',{name:'Payments',exact:true}).click();const section=page.locator('.payments');await section.getByRole('combobox',{name:'Payment quote context',exact:true}).selectOption(f.quoteId);await expect(section).toContainText('PAYMENT_PLAN_MISSING');
 await section.getByText('Configure new payment plan revision',{exact:true}).click();await section.getByRole('button',{name:'Add milestone',exact:true}).click();const advance=section.getByRole('group',{name:'Milestone 1',exact:true});await advance.getByLabel('Milestone title',{exact:true}).fill('TEST production advance');await advance.getByRole('combobox',{name:'Amount basis',exact:true}).selectOption('PERCENT');await advance.getByLabel('Milestone value',{exact:true}).fill('50');await advance.getByRole('combobox',{name:'Due trigger',exact:true}).selectOption('BEFORE_PRODUCTION_RELEASE');await advance.getByLabel('Required for future Production Release',{exact:true}).check();await advance.getByLabel('Customer visible',{exact:true}).check();
 await section.getByRole('button',{name:'Add milestone',exact:true}).click();const design=section.getByRole('group',{name:'Milestone 2',exact:true});await design.getByLabel('Milestone title',{exact:true}).fill('TEST independent design');await design.getByLabel('Milestone value',{exact:true}).fill('25.123456');await design.getByRole('button',{name:'Move milestone up',exact:true}).click();await section.getByRole('group',{name:'Milestone 1',exact:true}).getByRole('button',{name:'Move milestone down',exact:true}).click();await section.getByLabel('Plan revision reason',{exact:true}).fill('TEST browser configured schedule');await section.getByRole('button',{name:'Save payment plan revision',exact:true}).click();await expect(section.getByRole('status')).toHaveText('Payment history saved.');await expect(section.locator('.payment-milestone').first()).toContainText('190.41');await expect(section.locator('.payment-milestone').last()).toContainText('25.12');
 await section.getByText('Report payment',{exact:true}).click();async function report(amount:string,reference:string){await section.getByLabel('Reported amount (RON)',{exact:true}).fill(amount);await section.getByLabel('Payment date',{exact:true}).fill('2026-10-03');await section.getByLabel('Payment method',{exact:true}).fill('TEST transfer');await section.getByLabel('Payment reference',{exact:true}).fill(reference);await section.getByRole('button',{name:'Record reported payment',exact:true}).click();const row=section.locator('.payment-record').filter({hasText:reference});await expect(row).toContainText('PAYMENT_REPORTED');return row;}
 const first=await report('100','TEST-PARTIAL-1');await expect(section).toContainText('PAYMENT_CONDITION_SATISFIED: No');await first.getByLabel('Confirmation / reversal reason',{exact:true}).fill('TEST receipt checked');await first.getByRole('button',{name:'Confirm reported payment',exact:true}).click();await expect(first.getByRole('heading')).toContainText('PAYMENT_CONFIRMED');await expect(section.locator('.payment-milestone').first()).toContainText('Outstanding: 90.41');
 const second=await report('90.41','TEST-PARTIAL-2');await second.getByLabel('Confirmation / reversal reason',{exact:true}).fill('TEST second receipt checked');await second.getByRole('button',{name:'Confirm reported payment',exact:true}).click();await expect(section).toContainText('PAYMENT_CONDITION_SATISFIED: Yes');await expect(section).toContainText('CLIENT_APPROVED: No');await page.screenshot({path:'test-results/payments-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await first.getByLabel('Confirmation / reversal reason',{exact:true}).fill('TEST reversal; correction required');await first.getByRole('button',{name:'Reverse confirmed payment',exact:true}).click();await expect(first.getByRole('heading')).toContainText('REVERSED');await expect(section).toContainText('PAYMENT_CONDITION_SATISFIED: No');await expect(section.locator('.payment-milestone').first()).toContainText('Outstanding: 100.00');await page.screenshot({path:'test-results/payments-mobile.png',fullPage:true});expect(errors).toEqual([]);
});
