import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('staff issues exact review; isolated customer requests changes and approves on desktop/mobile',async({page,context,browser})=>{
 const f=JSON.parse(await readFile('.local/portal-test-project.json','utf8')) as {projectId:string;versionId:string;quoteId:string;quoteNumber:number};
 async function route(c:typeof context){if(process.env.MOBLUX_TEST_API_ORIGIN)await c.route('**/api/**',async r=>{const u=new URL(r.request().url());const response=await r.fetch({url:process.env.MOBLUX_TEST_API_ORIGIN+u.pathname+u.search});await r.fulfill({response});});}
 await route(context);const customer=await browser.newContext({viewport:{width:1280,height:900}});await route(customer);const portal=await customer.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));portal.on('pageerror',e=>errors.push(e.message));
 try{
 await page.goto('/login');await page.getByLabel('Development access code').fill(process.env.DEV_LOGIN_CODE!);await page.getByRole('button',{name:'Open workspace'}).click();await expect(page.getByRole('heading',{name:'Make room for good work.'})).toBeVisible();
 await page.goto(`/projects/${f.projectId}`);await page.getByRole('tab',{name:'Client approval',exact:true}).click();const section=page.locator('.client-status');await section.getByRole('combobox',{name:'Review project version',exact:true}).selectOption(f.versionId);await section.getByRole('combobox',{name:'Quote to send',exact:true}).selectOption(f.quoteId);await section.getByLabel('Client project title',{exact:true}).fill('Your new living space');await section.getByLabel('Client contact name',{exact:true}).fill('Browser Client');await section.getByLabel('Client contact email',{exact:true}).fill('browser@example.test');await section.getByRole('button',{name:'Issue client access',exact:true}).click();await expect(section.getByLabel('New private client link')).toBeVisible();const link=await section.getByLabel('New private client link').inputValue();
 const requests:string[]=[];portal.on('request',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/'))requests.push(path);});await portal.goto(link);await expect(portal.getByRole('heading',{name:'Your new living space',exact:true})).toBeVisible();await expect.poll(()=>new URL(portal.url()).hash).toBe('');await expect(portal.getByText('PENDING_CLIENT',{exact:true})).toBeVisible();await expect.poll(()=>portal.locator('img').evaluateAll(imgs=>imgs.length>0&&imgs.every(i=>(i as HTMLImageElement).naturalWidth>0))).toBe(true);
 const text=await portal.locator('body').innerText();for(const marker of ['SENTINEL','PRIVATE_SOURCE','BOM','supplier','costing'])expect(text).not.toContain(marker);for(const path of requests)expect(path.startsWith('/api/client/')).toBe(true);
 await portal.getByRole('textbox',{name:'Requested changes',exact:true}).fill('Please confirm the handle finish.');await portal.getByRole('button',{name:'Request changes',exact:true}).click();await expect(portal.getByText('CHANGES_REQUESTED',{exact:true})).toBeVisible();await portal.screenshot({path:'test-results/portal-desktop.png',fullPage:true});
 await portal.setViewportSize({width:390,height:844});await expect.poll(()=>portal.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await portal.getByRole('button',{name:'Approve this proposal',exact:true}).click();await expect(portal.getByRole('group',{name:'Approval confirmation',exact:true})).toContainText(`quote ${f.quoteNumber}`);await portal.getByRole('button',{name:'Confirm approval',exact:true}).click();await expect(portal.getByText('APPROVED',{exact:true})).toBeVisible();await expect(portal.getByRole('button',{name:'Approve this proposal',exact:true})).toHaveCount(0);await portal.screenshot({path:'test-results/portal-mobile.png',fullPage:true});await portal.reload();await expect(portal.getByText('APPROVED',{exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await page.goto(`/projects/${f.projectId}`);await page.getByRole('tab',{name:'Client approval',exact:true}).click();const current=section.locator('article').filter({has:page.getByRole('heading',{name:'Your new living space · APPROVED',exact:true})});await expect(current).toContainText('Please confirm the handle finish.');await current.getByText('Immutable approval evidence',{exact:true}).click();await expect(current).toContainText(f.quoteId);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await current.getByRole('button',{name:'Revoke access',exact:true}).click();await expect(current).toContainText('REVOKED');await portal.reload();await expect(portal.locator('.client-portal').getByRole('alert')).toContainText('unavailable or expired');expect(errors).toEqual([]);
 }finally{await customer.close();}
});



