import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('quote builder saves manual offers and isolates the combined client preview on desktop/mobile',async({page,context})=>{
 const f=JSON.parse(await readFile('.local/quote-test-project.json','utf8')) as {projectId:string;versionId:string;nextVersionId:string};
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 await page.goto('/login');await page.getByLabel('Development access code').fill(process.env.DEV_LOGIN_CODE!);await page.getByRole('button',{name:'Open workspace'}).click();await expect(page.getByRole('heading',{name:'Make room for good work.'})).toBeVisible();
 await page.goto(`/projects/${f.projectId}`);await page.getByRole('tab',{name:'Quote',exact:true}).click();const editor=page.locator('.quote-builder');await editor.getByRole('combobox',{name:'Quote project version',exact:true}).selectOption(f.versionId);
 await expect(editor.getByLabel('Quote title',{exact:true})).toHaveValue('TEST commercial offer');await editor.getByLabel('Quote title',{exact:true}).fill('TEST reviewed commercial offer');await editor.getByLabel('VAT percentage',{exact:true}).fill('20');
 await editor.getByText('Quote sections (0)',{exact:true}).click();await editor.getByRole('button',{name:'Add quote section',exact:true}).click();const section=editor.getByRole('group',{name:'Quote section 1',exact:true});await section.getByLabel('Section title',{exact:true}).fill('Furniture and services');await section.getByLabel('Show section to customer').check();
 const line=editor.getByRole('group',{name:'Quote line 1',exact:true});await line.getByRole('combobox',{name:'Quote section',exact:true}).selectOption({label:'Furniture and services'});
 await editor.getByRole('button',{name:'Add quote line',exact:true}).click();const added=editor.getByRole('group',{name:'Quote line 4',exact:true});await added.getByLabel('Line title',{exact:true}).fill('Temporary service');await added.getByRole('button',{name:'Remove quote line',exact:true}).click();
 await editor.getByRole('group',{name:'Quote line 2',exact:true}).getByRole('button',{name:'Move up',exact:true}).click();await editor.getByRole('textbox',{name:'Internal quote notes',exact:true}).fill('BROWSER_PRIVATE_QUOTE');
 await expect(editor.locator('.quote-totals')).toContainText('380.82');await editor.getByRole('button',{name:'Save quote revision',exact:true}).click();await expect(editor.getByRole('status')).toHaveText('Quote revision saved.');
 const requests:string[]=[];context.on('page',p=>p.on('request',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/'))requests.push(path);}));const popup=context.waitForEvent('page');await editor.getByRole('link',{name:'View quote as client',exact:true}).click();const preview=await popup;
 await expect(preview.getByRole('heading',{name:'TEST reviewed commercial offer',exact:true})).toBeVisible();await expect(preview.getByRole('heading',{name:'Later presentation',exact:true})).toBeVisible();await expect(preview.locator('.quote-totals')).toContainText('380.82');await expect(preview.locator('.quote-totals')).toContainText('114.25');await expect(preview.locator('.quote-totals')).toContainText('266.57');
 const body=await preview.locator('body').innerText();for(const marker of ['SENTINEL','BROWSER_PRIVATE','Costing','BOM'])expect(body).not.toContain(marker);expect(requests.length).toBeGreaterThan(0);for(const path of requests)expect(path).toMatch(/\/quotes\/[a-f0-9-]+\/preview$/);
 await preview.screenshot({path:'test-results/quote-desktop.png',fullPage:true});await preview.setViewportSize({width:390,height:844});await expect.poll(()=>preview.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await preview.screenshot({path:'test-results/quote-mobile.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.goto(`/projects/${f.projectId}`);await page.getByRole('tab',{name:'Quote',exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await editor.getByRole('combobox',{name:'Quote project version',exact:true}).selectOption(f.nextVersionId);await expect(editor.getByLabel('Quote title',{exact:true})).toHaveValue('');await expect(editor.getByRole('link',{name:'View quote as client',exact:true})).toHaveCount(0);expect(errors).toEqual([]);await preview.close();
});


