import {add,canonical,money,multiply} from '../costing/decimal.js';
import {DomainError} from '../identity/policy.js';
import {planSchema,type Milestone,type MilestoneState,type ClientPaymentView} from '../../contracts/payments.js';
export const paymentAlgorithm='payment-plan/quote-gross/half-up-2/v1';
export function compare(a:string,b:string){const [aw,af='']=a.split('.'),[bw,bf='']=b.split('.'),n=Math.max(af.length,bf.length),x=BigInt(aw+af.padEnd(n,'0')),y=BigInt(bw+bf.padEnd(n,'0'));return x<y?-1:x>y?1:0;}
export function outstanding(amount:string,paid:string){if(compare(paid,amount)>=0)return '0';const [aw,af='']=amount.split('.'),[bw,bf='']=paid.split('.'),n=Math.max(af.length,bf.length),v=(BigInt(aw+af.padEnd(n,'0'))-BigInt(bw+bf.padEnd(n,'0'))).toString().padStart(n+1,'0');return canonical(n?v.slice(0,-n)+'.'+v.slice(-n):v);}
export function calculateMilestones(input:unknown,quoteTotal:string,currency:string):Milestone[]{const p=planSchema.parse(input);return p.milestones.map(m=>{if(compare(m.value,'0')<=0||m.basis==='PERCENT'&&compare(m.value,'100')>0)throw new DomainError(400,'Milestone values must be positive; a percentage cannot exceed 100.');if(m.requiredForProduction&&['BEFORE_INSTALLATION','AFTER_INSTALLATION','AFTER_CUSTOMER_ACCEPTANCE'].includes(m.trigger))throw new DomainError(400,'A later installation/acceptance trigger cannot be a prerequisite for production.');const amountExact=m.basis==='PERCENT'?multiply(multiply(quoteTotal,m.value),'0.01'):canonical(m.value),amount=money(amountExact);if(compare(amount,'0')<=0)throw new DomainError(400,'Milestone must be at least one currency cent.');return {...m,amountExact,amount,currency};});}
export function deriveMilestones(milestones:Milestone[],payments:{id:string;milestoneId:string;amount:string}[],events:{paymentId:string;action:'CONFIRMED'|'REVERSED'}[]):MilestoneState[]{return milestones.map(m=>{let confirmed='0',reported='0';for(const p of payments.filter(p=>p.milestoneId===m.id)){if(events.some(e=>e.paymentId===p.id&&e.action==='REVERSED'))continue;if(events.some(e=>e.paymentId===p.id&&e.action==='CONFIRMED'))confirmed=add(confirmed,p.amount);else reported=add(reported,p.amount);}const satisfied=compare(confirmed,m.amount)>=0;return {...m,confirmedAmount:confirmed,reportedAmount:reported,outstandingAmount:outstanding(m.amount,confirmed),satisfied,status:satisfied?'PAYMENT_CONFIRMED':compare(reported,'0')>0?'PAYMENT_REPORTED':'PAYMENT_DUE'};});}
export function paymentGate(milestones:MilestoneState[]|null){if(!milestones)return {satisfied:false,reason:'PAYMENT_PLAN_MISSING'};const required=milestones.filter(m=>m.requiredForProduction);if(!required.length)return {satisfied:false,reason:'PRODUCTION_PAYMENT_REQUIREMENT_NOT_CONFIGURED'};return {satisfied:required.every(m=>m.satisfied),reason:required.every(m=>m.satisfied)?'PAYMENT_CONDITION_SATISFIED':'REQUIRED_MILESTONES_OUTSTANDING'};}
export function clientPaymentProjection(planRevision:number,currency:string,milestones:MilestoneState[]):ClientPaymentView{return {planRevision,currency,milestones:milestones.filter(m=>m.visible).map(m=>({title:m.title,description:m.description,amount:m.amount,confirmedAmount:m.confirmedAmount,outstandingAmount:m.outstandingAmount,status:m.status,dueTrigger:m.trigger,customerNotes:m.customerNotes}))};}
