import {and,desc,eq,sql} from 'drizzle-orm';
import {db,type Transaction} from '../../infrastructure/db.js';
import * as s from '../../../database/schema.js';
import {authorize,DomainError,type Actor,type Capability} from '../identity/policy.js';
import {record} from '../audit/service.js';
import {evidenceHash} from '../portal/evidence.js';
import {planSchema,paymentReportSchema,paymentEventSchema} from '../../contracts/payments.js';
import {calculateMilestones,compare,deriveMilestones,paymentAlgorithm,paymentGate,clientPaymentProjection} from './calculation.js';
import {add} from '../costing/decimal.js';
function access(a:Actor,cap:Capability='payment.view'){authorize(a,'project.view');authorize(a,'payment.view');authorize(a,cap);}
const allowed=(a:Actor,c:string)=>a.grants.has(c)&&!a.denies.has(c);
async function lock(tx:Transaction,quoteId:string){await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`payments:${quoteId}`},0))`);}
async function quote(tx:Transaction,projectId:string,quoteId:string){const q=await tx.query.quoteVersions.findFirst({where:and(eq(s.quoteVersions.id,quoteId),eq(s.quoteVersions.projectId,projectId))});if(!q)throw new DomainError(404,'Quote not found.');return q;}
async function plan(tx:Transaction,projectId:string,planId:string){const p=await tx.query.paymentPlans.findFirst({where:and(eq(s.paymentPlans.id,planId),eq(s.paymentPlans.projectId,projectId))});if(!p)throw new DomainError(404,'Payment plan not found.');return p;}
async function latest(tx:Transaction,quoteId:string){return tx.query.paymentPlans.findFirst({where:eq(s.paymentPlans.quoteId,quoteId),orderBy:desc(s.paymentPlans.number)});}
async function current(tx:Transaction,p:typeof s.paymentPlans.$inferSelect){if((await latest(tx,p.quoteId))?.id!==p.id)throw new DomainError(409,'This payment plan is historical. No payment is moved to the revised plan.');}
export async function configure(a:Actor,projectId:string,quoteId:string,input:unknown){access(a,'payment.configure');const req=planSchema.parse(input),hash=evidenceHash(req);return db.transaction(async tx=>{
 await lock(tx,quoteId);const q=await quote(tx,projectId,quoteId);if(q.result.status!=='COMPLETE'||q.result.totals.withVat===null)throw new DomainError(400,'Payment plan needs a complete exact quote.');const old=await tx.query.paymentPlans.findFirst({where:and(eq(s.paymentPlans.quoteId,quoteId),eq(s.paymentPlans.requestId,req.requestId))});if(old){if(old.payloadHash!==hash)throw new DomainError(409,'Request already used with different content.');return old;}
 const previous=await latest(tx,quoteId);if((previous?.id??null)!==req.previousId)throw new DomainError(409,'Plan changed. Reload before saving.');
 const [p]=await tx.insert(s.paymentPlans).values({projectId,versionId:q.versionId,quoteId,number:(previous?.number??0)+1,previousId:req.previousId,requestId:req.requestId,payloadHash:hash,reason:req.reason,currency:q.content.currency,quoteTotal:q.result.totals.withVat,algorithm:paymentAlgorithm,milestones:calculateMilestones(req,q.result.totals.withVat,q.content.currency),createdBy:a.id}).returning();await record(tx,a.id,'payment.plan.revised',p.id,projectId,{quoteId,versionId:q.versionId,previousId:req.previousId,number:p.number,paymentsTransferred:false});return p;
});}
export async function report(a:Actor,projectId:string,planId:string,input:unknown){access(a,'payment.record');const req=paymentReportSchema.parse(input);if(compare(req.amount,'0')<=0)throw new DomainError(400,'Payment amount must be positive.');return db.transaction(async tx=>{
 const p=await plan(tx,projectId,planId);await lock(tx,p.quoteId);const hash=evidenceHash(req),old=await tx.query.paymentReports.findFirst({where:and(eq(s.paymentReports.planId,planId),eq(s.paymentReports.requestId,req.requestId))});if(old){if(old.payloadHash!==hash)throw new DomainError(409,'Request already used with different content.');return old;}await current(tx,p);
 if(!p.milestones.some(m=>m.id===req.milestoneId))throw new DomainError(400,'Milestone does not belong to this exact payment plan.');
 if(req.evidenceSourceId){authorize(a,'project.files.download');const file=await tx.query.sources.findFirst({where:and(eq(s.sources.id,req.evidenceSourceId),eq(s.sources.projectId,projectId),eq(s.sources.versionId,p.versionId))});if(!file)throw new DomainError(400,'Evidence must belong to this exact project version.');}
 const [payment]=await tx.insert(s.paymentReports).values({...req,planId,payloadHash:hash,currency:p.currency,createdBy:a.id}).returning();await record(tx,a.id,'payment.reported',payment.id,projectId,{planId,milestoneId:req.milestoneId,quoteId:p.quoteId});return payment;
});}
export async function event(a:Actor,projectId:string,paymentId:string,input:unknown){const req=paymentEventSchema.parse(input);access(a,req.action==='CONFIRMED'?'payment.confirm':'payment.reverse');return db.transaction(async tx=>{
 const payment=await tx.query.paymentReports.findFirst({where:eq(s.paymentReports.id,paymentId)});if(!payment)throw new DomainError(404,'Payment not found.');const p=await plan(tx,projectId,payment.planId);await lock(tx,p.quoteId);const events=await tx.select().from(s.paymentEvents).where(eq(s.paymentEvents.paymentId,paymentId)),hash=evidenceHash(req),old=events.find(e=>e.requestId===req.requestId);if(old){if(old.payloadHash!==hash)throw new DomainError(409,'Request already used with different content.');return old;}
 if(events.some(e=>e.action===req.action))throw new DomainError(409,'This action is already recorded.');if(req.action==='CONFIRMED')await current(tx,p);else if(!events.some(e=>e.action==='CONFIRMED'))throw new DomainError(409,'Only a confirmed payment can be reversed.');
 const [saved]=await tx.insert(s.paymentEvents).values({...req,paymentId,payloadHash:hash,createdBy:a.id}).returning();await record(tx,a.id,req.action==='CONFIRMED'?'payment.confirmed':'payment.reversed',saved.id,projectId,{paymentId,planId:p.id,quoteId:p.quoteId});return saved;
});}
async function planState(tx:Transaction,p:typeof s.paymentPlans.$inferSelect){const reports=await tx.select().from(s.paymentReports).where(eq(s.paymentReports.planId,p.id)),events=await tx.select({id:s.paymentEvents.id,paymentId:s.paymentEvents.paymentId,requestId:s.paymentEvents.requestId,action:s.paymentEvents.action,reason:s.paymentEvents.reason,createdBy:s.paymentEvents.createdBy,createdAt:s.paymentEvents.createdAt}).from(s.paymentEvents).innerJoin(s.paymentReports,eq(s.paymentReports.id,s.paymentEvents.paymentId)).where(eq(s.paymentReports.planId,p.id));const milestones=deriveMilestones(p.milestones,reports,events);return {plan:p,milestones,reports,events,gate:paymentGate(milestones),configuredTotal:p.milestones.reduce((n,m)=>add(n,m.amount),'0')};}
export async function state(a:Actor,projectId:string,quoteId:string){access(a);return db.transaction(async tx=>{
 const q=await quote(tx,projectId,quoteId),plans=await tx.select().from(s.paymentPlans).where(eq(s.paymentPlans.quoteId,quoteId)).orderBy(desc(s.paymentPlans.number)),history=[];for(const p of plans)history.push(await planState(tx,p));
 const snapshot=await tx.query.portalSnapshots.findFirst({where:and(eq(s.portalSnapshots.projectId,projectId),eq(s.portalSnapshots.quoteId,quoteId))}),approval=snapshot?await tx.query.portalActions.findFirst({where:and(eq(s.portalActions.snapshotId,snapshot.id),eq(s.portalActions.action,'APPROVE'))}):null,superseded=snapshot?!!await tx.query.portalSupersessions.findFirst({where:eq(s.portalSupersessions.snapshotId,snapshot.id)}):false;
 const evidenceOptions=allowed(a,'project.files.download')?await tx.select({id:s.sources.id,name:s.sources.name,hash:s.sources.hash}).from(s.sources).where(and(eq(s.sources.projectId,projectId),eq(s.sources.versionId,q.versionId))):[];
 return {quoteId,versionId:q.versionId,quoteNumber:q.number,quoteTotal:q.result.totals.withVat,currency:q.content.currency,clientApproved:!!approval&&!superseded,historicalApprovalId:approval?.id??null,approvalSuperseded:superseded,paymentCondition:history[0]?.gate??paymentGate(null),history,evidenceOptions,canConfigure:allowed(a,'payment.configure'),canRecord:allowed(a,'payment.record'),canConfirm:allowed(a,'payment.confirm'),canReverse:allowed(a,'payment.reverse')};
});}
/** Staff-only inspection of the future client contract. No new portal entitlement or publication. */
export async function safePreview(a:Actor,projectId:string,planId:string){access(a);return db.transaction(async tx=>{const p=await plan(tx,projectId,planId),state=await planState(tx,p);return clientPaymentProjection(p.number,p.currency,state.milestones);});}
export async function options(a:Actor,projectId:string){access(a);const rows=await db.select({id:s.quoteVersions.id,number:s.quoteVersions.number,versionNumber:s.versions.number,title:s.quoteVersions.content}).from(s.quoteVersions).innerJoin(s.versions,eq(s.versions.id,s.quoteVersions.versionId)).where(eq(s.quoteVersions.projectId,projectId)).orderBy(desc(s.versions.number),desc(s.quoteVersions.number));return rows.map(r=>({id:r.id,number:r.number,versionNumber:r.versionNumber,title:r.title.title}));}
