import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import pg from 'pg';
import {buildServer} from '../../apps/api/server.js';
import {pool} from '../../packages/infrastructure/db.js';
import {paymentPlanFixture} from '../fixtures/payments.js';
import {quoteFixture} from '../fixtures/quote.js';
import {presentationFixture} from '../fixtures/presentation.js';
test('payments keep exact quotes, explicit confirmation, partial allocations, reversals, permissions and history',async()=>{
 const app=buildServer(),owner=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),headers:Record<string,string>={origin:process.env.APP_ORIGIN!};
 try{
 const login=await app.inject({method:'POST',url:'/api/auth/login',headers,payload:{code:process.env.DEV_LOGIN_CODE}});assert.equal(login.statusCode,200);headers.cookie=`${login.cookies[0].name}=${login.cookies[0].value}`;const user=(await app.inject({url:'/api/me',headers})).json();
 async function post(url:string,payload:object,h=headers){const r=await app.inject({method:'POST',url,headers:h,payload});assert.ok(r.statusCode<300,r.body);return r.json();}
 const customer=await post('/api/customers',{name:'[TEST] Payments',email:'',phone:'',address:''}),project=await post('/api/projects',{customerId:customer.id,name:'[TEST] Payment conditions',description:''}),v=await post(`/api/projects/${project.id}/versions`,{summary:'Payment test',requestId:randomUUID()}),base=`/api/projects/${project.id}`,versionBase=`${base}/versions/${v.id}`,p=await post(versionBase+'/presentations',{requestId:randomUUID(),previousId:null,content:presentationFixture()}),qc=quoteFixture(),q=await post(versionBase+'/quotes',{requestId:randomUUID(),previousId:null,presentationRevisionId:p.id,content:qc}),url=`${base}/quotes/${q.id}`;
 const fingerprint=async()=>(await owner.query('select md5(row_to_json(q)::text) h from quote_versions q where id=$1',[q.id])).rows[0].h,before=await fingerprint();
 async function state(){const r=await app.inject({url:url+'/payments',headers});assert.equal(r.statusCode,200,r.body);return r.json();}
 assert.equal((await state()).paymentCondition.reason,'PAYMENT_PLAN_MISSING');assert.equal((await state()).clientApproved,false);
 const config=paymentPlanFixture(),plan=await post(url+'/payment-plans',config);assert.equal(plan.milestones[0].amount,'190.41');assert.equal((await post(url+'/payment-plans',config)).id,plan.id);assert.equal((await app.inject({method:'POST',url:url+'/payment-plans',headers,payload:{...config,reason:'different'}})).statusCode,409);
 const grant=await post(base+'/client-access',{requestId:randomUUID(),quoteId:q.id,projectTitle:'Test commercial plan',contactName:'Test client',contactEmail:'payment@example.test',expiresInHours:24}),redeemed=await app.inject({method:'POST',url:'/api/client/redeem',headers:{origin:headers.origin},payload:{token:grant.token}});assert.equal(redeemed.statusCode,200);const client={origin:headers.origin,cookie:`moblux_client=${redeemed.cookies[0].value}`},snapshot=(await app.inject({url:'/api/client/snapshot',headers:client})).json();await post('/api/client/actions',{action:'APPROVE',requestId:randomUUID(),snapshotId:snapshot.snapshotId,hash:snapshot.hash,confirmed:true},client);assert.equal((await state()).clientApproved,true);assert.equal((await state()).paymentCondition.satisfied,false);
 const report={requestId:randomUUID(),milestoneId:plan.milestones[0].id,amount:'100.123456',paymentDate:'2026-10-03',method:'TEST bank transfer',reference:'TEST-REF',evidenceSourceId:null,internalNote:'PAYMENT_INTERNAL_SENTINEL'},r1=await post(`${base}/payment-plans/${plan.id}/reports`,report);assert.equal((await post(`${base}/payment-plans/${plan.id}/reports`,report)).id,r1.id);assert.equal((await state()).history[0].milestones[0].confirmedAmount,'0');assert.equal((await state()).history[0].milestones[0].status,'PAYMENT_REPORTED');
 const confirmation={requestId:randomUUID(),action:'CONFIRMED',reason:'TEST verified receipt'};await Promise.all([post(`${base}/payments/${r1.id}/events`,confirmation),post(`${base}/payments/${r1.id}/events`,confirmation)]);assert.equal((await state()).history[0].milestones[0].outstandingAmount,'90.286544');const r2=await post(`${base}/payment-plans/${plan.id}/reports`,{...report,requestId:randomUUID(),amount:'90.286544'});await post(`${base}/payments/${r2.id}/events`,{...confirmation,requestId:randomUUID()});assert.equal((await state()).paymentCondition.satisfied,true);
 const reverse={requestId:randomUUID(),action:'REVERSED',reason:'TEST incorrect reference; full reversal'};await post(`${base}/payments/${r1.id}/events`,reverse);await post(`${base}/payments/${r1.id}/events`,reverse);assert.equal((await state()).paymentCondition.satisfied,false);assert.equal((await state()).history[0].milestones[0].confirmedAmount,'90.286544');await assert.rejects(owner.query('update payment_reports set amount=$1 where id=$2',['0',r1.id]),/immutable/i);await assert.rejects(owner.query('delete from payment_events where payment_id=$1',[r1.id]),/immutable/i);
 const safe=await app.inject({url:`${base}/payment-plans/${plan.id}/client-preview`,headers});assert.equal(safe.statusCode,200);for(const marker of ['SENTINEL','internalNote','createdBy','reference','evidenceSourceId','Design service'])assert.ok(!safe.body.includes(marker),marker);
 const replacement=await post(url+'/payment-plans',{...config,requestId:randomUUID(),previousId:plan.id,reason:'TEST revised obligations; no transfer'});assert.equal((await state()).history[0].reports.length,0);assert.equal((await state()).history[1].reports.length,2);assert.equal((await state()).paymentCondition.satisfied,false);assert.equal((await app.inject({method:'POST',url:`${base}/payment-plans/${plan.id}/reports`,headers,payload:{...report,requestId:randomUUID()}})).statusCode,409);
 await post(`${base}/payments/${r2.id}/events`,{...reverse,requestId:randomUUID()});assert.equal((await state()).history[1].milestones[0].confirmedAmount,'0');
 const other=await post('/api/projects',{customerId:customer.id,name:'[TEST] Other payment project',description:''});assert.equal((await app.inject({url:`/api/projects/${other.id}/quotes/${q.id}/payments`,headers})).statusCode,404);assert.equal((await app.inject({method:'POST',url:`${base}/payment-plans/${replacement.id}/reports`,headers,payload:{...report,requestId:randomUUID(),milestoneId:randomUUID()}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:`${base}/payment-plans/${replacement.id}/reports`,headers,payload:{...report,requestId:randomUUID(),evidenceSourceId:randomUUID()}})).statusCode,400);
 const boundary='payment-evidence',uploaded=await app.inject({method:'POST',url:versionBase+'/sources',headers:{...headers,'idempotency-key':randomUUID(),'content-type':`multipart/form-data; boundary=${boundary}`},payload:Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="test-payment-proof.pdf"\r\nContent-Type: application/pdf\r\n\r\n%PDF-1.4 TEST payment evidence only\r\n--${boundary}--\r\n`)});assert.equal(uploaded.statusCode,201,uploaded.body);
 const evidenceId=(await owner.query('select id from source_files where project_id=$1 and name=$2',[project.id,'test-payment-proof.pdf'])).rows[0].id;
 const reportUrl=`${base}/payment-plans/${replacement.id}/reports`,r3=await post(reportUrl,{...report,requestId:randomUUID(),amount:'10',evidenceSourceId:evidenceId});assert.equal(r3.evidenceSourceId,evidenceId);assert.equal(r3.createdBy,user.id);assert.equal((await state()).evidenceOptions[0].id,evidenceId);
 await owner.query('insert into user_overrides(user_id,capability,allowed) values($1,$2,false)',[user.id,'project.files.download']);try{assert.equal((await state()).evidenceOptions.length,0);assert.equal((await app.inject({method:'POST',url:reportUrl,headers,payload:{...report,requestId:randomUUID(),evidenceSourceId:evidenceId}})).statusCode,403);}finally{await owner.query('delete from user_overrides where user_id=$1 and capability=$2',[user.id,'project.files.download']);}
 for(const [cap,method,path,payload] of [['payment.view','GET',url+'/payments',null],['payment.configure','POST',url+'/payment-plans',{...config,requestId:randomUUID(),previousId:replacement.id}],['payment.record','POST',reportUrl,{...report,requestId:randomUUID()}],['payment.confirm','POST',`${base}/payments/${r3.id}/events`,{...confirmation,requestId:randomUUID()}],['payment.reverse','POST',`${base}/payments/${r3.id}/events`,{...reverse,requestId:randomUUID()}]] as const){await owner.query('insert into user_overrides(user_id,capability,allowed) values($1,$2,false)',[user.id,cap]);try{assert.equal((await app.inject({method,url:path,headers,...(payload?{payload}:{})})).statusCode,403);}finally{await owner.query('delete from user_overrides where user_id=$1 and capability=$2',[user.id,cap]);}}
 assert.equal((await app.inject({url:url+'/payments',headers:client})).statusCode,401);assert.equal((await app.inject({method:'POST',url:reportUrl,headers:{cookie:headers.cookie},payload:{...report,requestId:randomUUID()}})).statusCode,403);
 const q2=await post(versionBase+'/quotes',{requestId:randomUUID(),previousId:q.id,presentationRevisionId:p.id,content:{...qc,title:'[TEST] Browser payment quote'}});const empty=(await app.inject({url:`${base}/quotes/${q2.id}/payments`,headers})).json();assert.equal(empty.clientApproved,false);assert.equal(empty.paymentCondition.satisfied,false);assert.equal(empty.history.length,0);assert.equal(await fingerprint(),before);assert.equal((await owner.query("select count(*)::int n from audit_events where event='payment.reported' and entity_id=$1",[r1.id])).rows[0].n,1);
 await writeFile('.local/payments-test-project.json',JSON.stringify({projectId:project.id,quoteId:q2.id}));
 }finally{await app.close();await owner.end();await pool.end();}
});
