import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import pg from 'pg';
import {buildServer} from '../../apps/api/server.js';
import {pool} from '../../packages/infrastructure/db.js';
import {quoteFixture} from '../fixtures/quote.js';
import {presentationFixture,imageFixture} from '../fixtures/presentation.js';
import {evidenceHash} from '../../packages/modules/portal/evidence.js';
test('portal exact snapshots, single-use access, S3 media, feedback, approval, supersession and isolation',async()=>{
 const app=buildServer(),owner=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL}),staff:Record<string,string>={origin:process.env.APP_ORIGIN!};
 try{
 const login=await app.inject({method:'POST',url:'/api/auth/login',headers:staff,payload:{code:process.env.DEV_LOGIN_CODE}});assert.equal(login.statusCode,200);staff.cookie=`${login.cookies[0].name}=${login.cookies[0].value}`;const user=(await app.inject({url:'/api/me',headers:staff})).json();
 async function post(url:string,payload:object,headers=staff){const r=await app.inject({method:'POST',url,headers,payload});assert.ok(r.statusCode<300,r.body);return r.json();}
 const c=await post('/api/customers',{name:'[TEST] Portal customer',email:'',phone:'',address:''}),p=await post('/api/projects',{customerId:c.id,name:'INTERNAL_PROJECT_SENTINEL',description:'INTERNAL_COST_SENTINEL'}),v=await post(`/api/projects/${p.id}/versions`,{summary:'INTERNAL_VERSION_SENTINEL',requestId:randomUUID()}),base=`/api/projects/${p.id}/versions/${v.id}`,accessUrl=`/api/projects/${p.id}/client-access`;
 const fingerprint=async()=>(await owner.query('select md5(row_to_json(v)::text) h from project_versions v where id=$1',[v.id])).rows[0].h,before=await fingerprint();
 async function upload(){const boundary='portal-image',r=await app.inject({method:'POST',url:base+'/presentations/media?kind=RENDER&provenance=PRIVATE_SOURCE_SENTINEL',headers:{...staff,'idempotency-key':randomUUID(),'content-type':`multipart/form-data; boundary=${boundary}`},payload:Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="private.png"\r\nContent-Type: image/png\r\n\r\n`),imageFixture(),Buffer.from(`\r\n--${boundary}--\r\n`)] )});assert.equal(r.statusCode,201,r.body);return r.json().id as string;}
 const imageId=await upload(),hiddenId=await upload(),pc=presentationFixture();pc.media=[{assetId:imageId,sectionId:null,caption:'Project render',visibility:'CLIENT_PRESENTATION'},{assetId:hiddenId,sectionId:null,caption:'HIDDEN_IMAGE_SENTINEL',visibility:'INTERNAL_ONLY'}];pc.coverAssetId=imageId;
 const presentation=await post(base+'/presentations',{requestId:randomUUID(),previousId:null,content:pc}),qc=quoteFixture(),q=await post(base+'/quotes',{requestId:randomUUID(),previousId:null,presentationRevisionId:presentation.id,content:qc});
 const req={requestId:randomUUID(),quoteId:q.id,projectTitle:'TEST customer home',contactName:'Test Client',contactEmail:'client@example.test',expiresInHours:24};const issued=await post(accessUrl,req);assert.equal((await post(accessUrl,req)).token,null);assert.equal((await app.inject({method:'POST',url:accessUrl,headers:staff,payload:{...req,projectTitle:'Different'}})).statusCode,409);
 async function redeem(token:string){const r=await app.inject({method:'POST',url:'/api/client/redeem',headers:{origin:staff.origin},payload:{token}});assert.equal(r.statusCode,200,r.body);assert.ok(r.headers['set-cookie']?.toString().includes('HttpOnly'));return {origin:staff.origin,cookie:`moblux_client=${r.cookies[0].value}`};}
 const client=await redeem(issued.token);assert.equal((await app.inject({method:'POST',url:'/api/client/redeem',headers:{origin:staff.origin},payload:{token:issued.token}})).statusCode,401);
 async function view(headers=client){const r=await app.inject({url:'/api/client/snapshot',headers});assert.equal(r.statusCode,200,r.body);return r.json();}
 const visible=await view();assert.equal(visible.status,'PENDING_CLIENT');assert.equal(visible.hash,evidenceHash(visible.content));assert.equal(visible.content.quote.totals.withVat,'380.82');
 const serialized=JSON.stringify(visible);for(const marker of ['SENTINEL','internalNote','contentHash','supplier','costing','algorithmVersion','objectKey','createdBy','contactEmail','evidence','partCount'])assert.ok(!serialized.includes(marker),marker);assert.equal(visible.content.quote.presentation.media.length,1);
 const imagePath=visible.content.quote.presentation.coverUrl,r=await app.inject({url:imagePath,headers:client});assert.equal(r.statusCode,200);assert.ok(!r.rawPayload.includes(Buffer.from('INTERNAL_METADATA')));assert.equal((await app.inject({url:imagePath.replace(imageId,hiddenId),headers:client})).statusCode,404);assert.equal((await app.inject({url:imagePath.replace(visible.snapshotId,randomUUID()),headers:client})).statusCode,404);
 for(const path of ['/api/me','/api/projects',`/api/projects/${p.id}`,accessUrl,base+'/quotes',base+'/presentations'])assert.equal((await app.inject({url:path,headers:client})).statusCode,401,path);assert.equal((await app.inject({url:'/api/client/snapshot',headers:staff})).statusCode,401);
 const feedback={action:'REQUEST_CHANGES',requestId:randomUUID(),snapshotId:visible.snapshotId,hash:visible.hash,message:'Please revise the handles.'};await post('/api/client/actions',feedback,client);await post('/api/client/actions',feedback,client);assert.equal((await view()).status,'CHANGES_REQUESTED');assert.equal((await app.inject({method:'POST',url:'/api/client/actions',headers:client,payload:{...feedback,requestId:randomUUID(),snapshotId:randomUUID()}})).statusCode,409);assert.equal((await app.inject({method:'POST',url:'/api/client/actions',headers:{cookie:client.cookie},payload:feedback})).statusCode,403);
 const approval={action:'APPROVE',requestId:randomUUID(),snapshotId:visible.snapshotId,hash:visible.hash,confirmed:true};await Promise.all([post('/api/client/actions',approval,client),post('/api/client/actions',approval,client)]);assert.equal((await view()).status,'APPROVED');assert.equal((await app.inject({method:'POST',url:'/api/client/actions',headers:client,payload:{...feedback,requestId:randomUUID()}})).statusCode,409);
 const saved=(await owner.query("select * from portal_actions where snapshot_id=$1 and action='APPROVE'",[visible.snapshotId])).rows;assert.equal(saved.length,1);assert.deepEqual(saved[0].approved_content,visible.content);await assert.rejects(owner.query('update portal_actions set message=$1 where id=$2',['changed',saved[0].id]),/immutable/i);await assert.rejects(owner.query('delete from portal_snapshots where id=$1',[visible.snapshotId]),/immutable/i);
 const q2=await post(base+'/quotes',{requestId:randomUUID(),previousId:q.id,presentationRevisionId:presentation.id,content:{...qc,title:'Later quote'}});assert.equal((await view()).status,'APPROVED');assert.equal((await view()).content.quote.quoteNumber,1);
 const laterVersion=await post(`/api/projects/${p.id}/versions`,{summary:'Later technical revision',requestId:randomUUID()});assert.equal((await view()).content.quote.projectVersionNumber,1);assert.equal((await owner.query('select count(*)::int n from portal_snapshots where version_id=$1',[laterVersion.id])).rows[0].n,0);
 const issue2=await post(accessUrl,{...req,requestId:randomUUID(),quoteId:q2.id}),client2=await redeem(issue2.token),view2=await view(client2);assert.equal(view2.status,'PENDING_CLIENT');assert.equal((await view()).status,'SUPERSEDED');assert.equal((await app.inject({method:'POST',url:'/api/client/actions',headers:client,payload:{...approval,requestId:randomUUID()}})).statusCode,409);
 const reissued=await post(accessUrl,{...req,requestId:randomUUID(),quoteId:q2.id});assert.equal((await app.inject({url:'/api/client/snapshot',headers:client2})).statusCode,401);assert.equal((await app.inject({url:view2.content.quote.presentation.coverUrl,headers:client2})).statusCode,401);const client3=await redeem(reissued.token);await post(`${accessUrl}/${reissued.accessId}/revoke`,{});assert.equal((await app.inject({url:'/api/client/snapshot',headers:client3})).statusCode,401);
 const expiredToken=randomBytes(32).toString('base64url');await owner.query('insert into portal_accesses(snapshot_id,request_id,payload_hash,token_hash,contact_name,contact_email,expires_at,created_by) values($1,$2,$3,$4,$5,$6,now()-interval \'1 hour\',$7)',[view2.snapshotId,randomUUID(),'test',createHash('sha256').update(expiredToken).digest('hex'),'TEST expired','expired@example.test',user.id]);assert.equal((await app.inject({method:'POST',url:'/api/client/redeem',headers:{origin:staff.origin},payload:{token:expiredToken}})).statusCode,401);
 const logoutAccess=await post(accessUrl,{...req,requestId:randomUUID(),quoteId:q2.id,contactEmail:'logout@example.test'}),logoutClient=await redeem(logoutAccess.token);await post('/api/client/logout',{},logoutClient);assert.equal((await app.inject({url:'/api/client/snapshot',headers:logoutClient})).statusCode,401);
 const expiring=await post(accessUrl,{...req,requestId:randomUUID(),quoteId:q2.id,contactEmail:'session-expired@example.test'}),expiredSession=randomBytes(32).toString('base64url');await owner.query('insert into portal_sessions(token_hash,access_id,expires_at) values($1,$2,now()-interval \'1 minute\')',[createHash('sha256').update(expiredSession).digest('hex'),expiring.accessId]);assert.equal((await app.inject({url:'/api/client/snapshot',headers:{cookie:`moblux_client=${expiredSession}`}})).statusCode,401);
 for(const capability of ['portal.manage','portal.view']){await owner.query('insert into user_overrides(user_id,capability,allowed) values($1,$2,false)',[user.id,capability]);try{const response=await app.inject(capability==='portal.view'?{url:accessUrl,headers:staff}:{method:'POST',url:accessUrl,headers:staff,payload:{...req,requestId:randomUUID(),quoteId:q2.id}});assert.equal(response.statusCode,403);}finally{await owner.query('delete from user_overrides where user_id=$1 and capability=$2',[user.id,capability]);}}
 const other=await post('/api/projects',{customerId:c.id,name:'[TEST] Other project',description:''});assert.equal((await app.inject({method:'POST',url:`/api/projects/${other.id}/client-access`,headers:staff,payload:{...req,requestId:randomUUID(),quoteId:q2.id}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:`/api/projects/${other.id}/client-access/${issued.accessId}/revoke`,headers:staff,payload:{}})).statusCode,404);
 assert.equal(await fingerprint(),before);assert.deepEqual((await owner.query('select approved_content from portal_actions where id=$1',[saved[0].id])).rows[0].approved_content,visible.content);
 const state=await app.inject({url:accessUrl,headers:staff});assert.equal(state.statusCode,200);assert.ok(state.body.includes('Please revise the handles.'));assert.ok(!state.body.includes('tokenHash'));assert.ok(!state.body.includes(issued.token));
 const q3=await post(base+'/quotes',{requestId:randomUUID(),previousId:q2.id,presentationRevisionId:presentation.id,content:{...qc,title:'TEST browser proposal'}});
 await writeFile('.local/portal-test-project.json',JSON.stringify({projectId:p.id,versionId:v.id,quoteId:q3.id,quoteNumber:3}));
 }finally{await app.close();await owner.end();await pool.end();}
});
