'use client';
import {useEffect,useRef,useState} from 'react';
import type {PortalView} from '../../../packages/contracts/portal';
import {QuoteView} from './quote-preview';
async function client<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(`/api/client/${path}`,{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Client access unavailable.');return data;}
export function ClientPortal(){
 const started=useRef(false),[data,setData]=useState<PortalView>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{if(started.current)return;started.current=true;const token=new URLSearchParams(location.hash.slice(1)).get('access');history.replaceState(null,'',location.pathname);void(async()=>{try{if(token)await client('redeem',{token});setData(await client<PortalView>('snapshot'));}catch(e){setError((e as Error).message);}})();},[]);
 async function action(kind:'APPROVE'|'REQUEST_CHANGES'){if(!data)return;setBusy(true);setError('');try{await client('actions',{action:kind,requestId:crypto.randomUUID(),snapshotId:data.snapshotId,hash:data.hash,...(kind==='APPROVE'?{confirmed:true}:{message})});setData(await client<PortalView>('snapshot'));setConfirm(false);setMessage('');setNotice(kind==='APPROVE'?'Approval recorded for these exact revisions.':'Your change request has been recorded.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="presentation-preview client-portal"><p>MOBLUX · Client review</p>{error&&<p role="alert">{error}</p>}{data?<><header className="panel padded"><h1>{data.content.projectTitle}</h1><p>Project V{data.content.quote.projectVersionNumber} · Presentation {data.content.presentationNumber} · Quote {data.content.quote.quoteNumber}</p><strong>{data.status}</strong>{data.approvedAt&&<p>Approved {new Date(data.approvedAt).toLocaleString()}</p>}<p>Client approval does not confirm payment or authorize production.</p><button onClick={()=>void client('logout',{}).then(()=>{setData(undefined);setNotice('Signed out. Request a new access link to return.');})}>Sign out</button></header><QuoteView data={data.content.quote}/>{['PENDING_CLIENT','CHANGES_REQUESTED'].includes(data.status)&&<section className="panel padded presentation-editor"><h2>Your response</h2><label>Requested changes<textarea value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)}/></label><button disabled={busy||!message.trim()} onClick={()=>void action('REQUEST_CHANGES')}>Request changes</button><div className="divider"/><button disabled={busy} onClick={()=>setConfirm(true)}>Approve this proposal</button>{confirm&&<div role="group" aria-label="Approval confirmation"><p>{data.content.confirmation}</p><button disabled={busy} onClick={()=>void action('APPROVE')}>Confirm approval</button><button disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></div>}</section>}</>:!error&&!notice&&<p>Opening secure review…</p>}{notice&&<p role="status">{notice}</p>}</main>;
}

