'use client';
import {useEffect,useState} from 'react';
import {api} from './api';
import type {QuoteState} from '../../../packages/contracts/quote';
import type {PortalSnapshot,PortalStatus} from '../../../packages/contracts/portal';
interface State {canManage:boolean;entries:{id:string;versionId:string;quoteId:string;presentationId:string;contentHash:string;content:PortalSnapshot;status:PortalStatus;accesses:{id:string;contactName:string;contactEmail:string;issuedAt:string;expiresAt:string;state:string}[];actions:{id:string;accessId:string;action:string;message:string|null;createdAt:string;contentHash:string;approvedContent:PortalSnapshot|null}[]}[];}
export function ClientStatus({projectId,versions}:{projectId:string;versions:{id:string;number:number}[]}){
 const [state,setState]=useState<State>(),[version,setVersion]=useState(versions[0]?.id??''),[quotes,setQuotes]=useState<QuoteState>(),[quote,setQuote]=useState(''),[title,setTitle]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[hours,setHours]=useState('24'),[link,setLink]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const base=`/projects/${projectId}/client-access`;async function reload(){setState(await api<State>(base));}
 useEffect(()=>{api<State>(base).then(setState).catch(e=>setError(e.message));},[base]);
 useEffect(()=>{setQuotes(undefined);setQuote('');if(!version)return;let active=true;api<QuoteState>(`/projects/${projectId}/versions/${version}/quotes`).then(q=>{if(active)setQuotes(q);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[projectId,version]);
 async function issue(){setBusy(true);setError('');setLink('');try{const result=await api<{token:string|null}>(base,{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID(),quoteId:quote,projectTitle:title,contactName:name,contactEmail:email,expiresInHours:Number(hours)})});if(result.token)setLink(`${location.origin}/client#access=${result.token}`);await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel padded presentation-editor client-status"><h2>Client status / Approval</h2>{error&&<p role="alert">{error}</p>}{state?.canManage&&<fieldset disabled={busy}><legend>Issue / reissue exact snapshot access</legend><label>Client project title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Review project version<select value={version} onChange={e=>setVersion(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>V{v.number}</option>)}</select></label><label>Quote to send<select value={quote} onChange={e=>{setQuote(e.target.value);const old=state.entries.find(s=>s.quoteId===e.target.value);if(old)setTitle(old.content.projectTitle);}}><option value="">Select exact quote</option>{quotes?.history.filter(q=>q.presentationRevisionId&&q.result.status==='COMPLETE').map(q=><option key={q.id} value={q.id}>Quote {q.number} · {q.content.title}</option>)}</select></label><label>Client contact name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Client contact email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Access lifetime (hours, 1–168)<input type="number" min={1} max={168} value={hours} onChange={e=>setHours(e.target.value)}/></label><p>Publishing a different quote explicitly supersedes earlier sent snapshots. Reissuing to the same contact revokes their previous link and session. No email is sent automatically.</p><button disabled={!quote||!title.trim()||!name.trim()||!email.trim()} onClick={()=>void issue()}>Issue client access</button></fieldset>}{link&&<div role="status"><p>Copy this private, single-use link for the intended contact. It is shown only now.</p><textarea aria-label="New private client link" readOnly value={link}/></div>}
 {state?.entries.map(entry=><article key={entry.id} className="presentation-room"><h3>{entry.content.projectTitle} · {entry.status}</h3><p>Project V{entry.content.quote.projectVersionNumber} · Presentation {entry.content.presentationNumber} · Quote {entry.content.quote.quoteNumber}</p>{entry.accesses.map(a=><div key={a.id}><p>{a.contactName} ({a.contactEmail}) · {a.state} · issued {new Date(a.issuedAt).toLocaleString()} · expires {new Date(a.expiresAt).toLocaleString()}</p>{state.canManage&&a.state==='ACTIVE'&&<button disabled={busy} onClick={()=>{setBusy(true);void api(`${base}/${a.id}/revoke`,{method:'POST',body:'{}'}).then(reload).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Revoke access</button>}</div>)}{entry.actions.map(a=><div key={a.id}><p>{a.action} · {new Date(a.createdAt).toLocaleString()} · {entry.accesses.find(g=>g.id===a.accessId)?.contactName}</p>{a.message&&<p className="preserve">{a.message}</p>}{a.approvedContent&&<details><summary>Immutable approval evidence</summary><p>ProjectVersion: {entry.versionId}<br/>PresentationRevision: {entry.presentationId}<br/>QuoteVersion: {entry.quoteId}<br/>Snapshot SHA-256: {a.contentHash}</p><pre className="library-raw">{JSON.stringify(a.approvedContent,null,2)}</pre></details>}</div>)}</article>)}{state&&!state.entries.length&&<p>No client snapshot issued.</p>}</section>;
}
