'use client';
import type {CostConfiguration,CostState,OperationPriceFamily,WorkstationCostPlaceholder} from '../../../packages/contracts/costing';
export const emptyCostConfiguration=():CostConfiguration=>({version:1,glass:[],doubling:[],edges:[],cutting:{mode:'INTERNAL',externalUnit:'service',externalQuantity:null,evidence:''},families:[],workstations:[]});
const stationFields=['purchaseCost','usefulLifeYears','productiveHoursPerYear','laborPerHour','energyPerHour','toolingPerHour','maintenancePerYear','allocatedOverheadPerYear'] as const;
const stationLabels=['Purchase cost','Useful life (years)','Productive hours / year','Labor / hour','Energy / hour','Tooling / hour','Maintenance / year','Allocated overhead / year'];
export function CostConfigurationEditor({value:c,onChange,disabled,state}:{value:CostConfiguration;onChange:(c:CostConfiguration)=>void;disabled:boolean;state:CostState}){
 const materials=state.materialOptions??[],targets=state.configurationTargets??[];
 const field=(label:string,value:string|null,change:(v:string|null)=>void,required=false)=><label>{label}<input disabled={disabled} value={value??''} placeholder={required?'Required evidence':'Unknown / missing'} onChange={e=>change(e.target.value||null)}/></label>;
 const material=(label:string,value:string,category:string,change:(v:string)=>void,thickness?:string)=><label>{label}<select disabled={disabled} value={value} onChange={e=>change(e.target.value)}><option value="">Select verified material</option>{materials.filter(m=>m.category===category&&(!thickness||Number(m.thickness)===Number(thickness))).map(m=><option key={m.id} value={m.id}>{m.name} · {m.thickness} mm · {m.id.slice(0,8)}</option>)}</select></label>;
 return <div aria-label="Cost rule configuration"><p>Sheet counts are the primary panel basis. Net BOM and optimization remain separate evidence. Save configuration first, then enter rates for its resulting selectors. Blank values remain missing.</p>
 <details><summary>Glass and doubled panels</summary>
 {c.glass.map((g,i)=><fieldset key={i}><legend>Glass exception {i+1}</legend>{material('Glass material',g.materialMasterId,'PANEL',v=>onChange({...c,glass:c.glass.map((x,n)=>n===i?{...x,materialMasterId:v}:x)}))}{field('Glass classification evidence',g.evidence,v=>onChange({...c,glass:c.glass.map((x,n)=>n===i?{...x,evidence:v??''}:x)}),true)}<button type="button" onClick={()=>onChange({...c,glass:c.glass.filter((_,n)=>n!==i)})}>Remove glass mapping</button></fieldset>)}
 <button type="button" disabled={disabled} onClick={()=>onChange({...c,glass:[...c.glass,{materialMasterId:'',evidence:''}]})}>Add glass exception</button>
 {c.doubling.map((d,i)=>{const patch=(v:Partial<typeof d>)=>onChange({...c,doubling:c.doubling.map((x,n)=>n===i?{...x,...v}:x)});return <fieldset key={i}><legend>Explicit 36 → 2 × 18 mm mapping {i+1}</legend>{material('Final 36 mm material',d.finalMaterialMasterId,'PANEL',v=>patch({finalMaterialMasterId:v}),'36')}{material('Layer 18 mm material',d.layerMaterialMasterId,'PANEL',v=>patch({layerMaterialMasterId:v}),'18')}{field('Doubling evidence and sheet allocation',d.evidence,v=>patch({evidence:v??''}),true)}{field('Allocated layer sheet count',d.layerSheets,v=>patch({layerSheets:v}))}{field('Verified layer sheet length mm',d.sheetLengthMm,v=>patch({sheetLengthMm:v}))}{field('Verified layer sheet width mm',d.sheetWidthMm,v=>patch({sheetWidthMm:v}))}<p>Two-layer net consumption; bonding on final face area once. Sheet allocation must exclude stock already charged for ordinary 18 mm panels. Edge demand stays at final thickness.</p><button type="button" onClick={()=>onChange({...c,doubling:c.doubling.filter((_,n)=>n!==i)})}>Remove doubling mapping</button></fieldset>;})}
 <button type="button" disabled={disabled} onClick={()=>onChange({...c,doubling:[...c.doubling,{finalMaterialMasterId:'',layerMaterialMasterId:'',finalThicknessMm:'36',layerThicknessMm:'18',evidence:'',layerSheets:null,sheetLengthMm:null,sheetWidthMm:null}]})}>Add explicit doubling mapping</button></details>
 <details><summary>Edge material basis and attributes</summary>{c.edges.map((e,i)=>{const patch=(v:Partial<typeof e>)=>onChange({...c,edges:c.edges.map((x,n)=>n===i?{...x,...v}:x)});return <fieldset key={i}><legend>Edge configuration {i+1}</legend>{material('Edge material',e.materialMasterId,'EDGE',v=>patch({materialMasterId:v}))}<label>Edge material basis<select value={e.basis} onChange={v=>patch({basis:v.target.value as 'm'|'roll'})}><option value="m">Meter</option><option value="roll">Whole roll</option></select></label>{field('Verified roll length m',e.rollLengthM,v=>patch({rollLengthM:v}))}{field('Verified edge width mm',e.widthMm,v=>patch({widthMm:v}))}{field('Verified edge type',e.type,v=>patch({type:v}))}{field('Edge evidence',e.evidence,v=>patch({evidence:v??''}),true)}<button type="button" onClick={()=>onChange({...c,edges:c.edges.filter((_,n)=>n!==i)})}>Remove edge configuration</button></fieldset>;})}<button type="button" disabled={disabled} onClick={()=>onChange({...c,edges:[...c.edges,{materialMasterId:'',basis:'m',rollLengthM:null,widthMm:null,type:null,evidence:''}]})}>Add edge configuration</button></details>
 <label>Cutting mode<select disabled={disabled} value={c.cutting.mode} onChange={e=>onChange({...c,cutting:{...c.cutting,mode:e.target.value as 'INTERNAL'|'EXTERNAL'}})}><option>INTERNAL</option><option>EXTERNAL</option></select></label>
 {c.cutting.mode==='EXTERNAL'&&<><label>External cutting unit<select value={c.cutting.externalUnit} onChange={e=>onChange({...c,cutting:{...c.cutting,externalUnit:e.target.value as 'm'|'service'}})}><option value="service">Configured service quantity</option><option value="m">Reported cutting meters</option></select></label>{c.cutting.externalUnit==='service'&&field('External cutting service quantity',c.cutting.externalQuantity,v=>onChange({...c,cutting:{...c.cutting,externalQuantity:v}}))}{field('External cutting evidence',c.cutting.evidence,v=>onChange({...c,cutting:{...c.cutting,evidence:v??''}}),true)}<p>External cutting replaces internal cutting; both are never charged.</p></>}
 <details><summary>Operation price families</summary><p>Assign exact source selectors to one active family per category. Diameter and literal depth selectors allow explicit Ø35 / through-hole families. No inferred face or operation semantics.</p>
 {c.families.map((f,i)=>{const patch=(v:Partial<OperationPriceFamily>)=>onChange({...c,families:c.families.map((x,n)=>n===i?{...x,...v}:x)});return <fieldset key={f.id}><legend>Family {i+1}</legend>{field('Family name',f.name,v=>patch({name:v??''}))}<label>Family active<input type="checkbox" checked={f.active} onChange={e=>patch({active:e.target.checked})}/></label><label>Family category<select value={f.category} onChange={e=>{const cat=e.target.value as OperationPriceFamily['category'];patch({category:cat,unit:cat==='DRILLING'?'hole':cat==='EDGE_SERVICE'?'m':'m2',memberKeys:[]});}}>{['DRILLING','GROOVE','ROUTING','EDGE_SERVICE'].map(x=><option key={x}>{x}</option>)}</select></label><label>Family basis<select value={f.unit} onChange={e=>patch({unit:e.target.value as OperationPriceFamily['unit']})}>{(f.category==='DRILLING'?['hole']:f.category==='EDGE_SERVICE'?['m']:['m2','m']).map(x=><option key={x}>{x}</option>)}</select></label>{field('Family configured rate',f.rate,v=>patch({rate:v}))}{field('Family assignment evidence',f.evidence,v=>patch({evidence:v??''}),true)}
 {targets.filter(t=>t.category===f.category).map(t=><label key={t.key}><input type="checkbox" checked={f.memberKeys.includes(t.key)} onChange={e=>patch({memberKeys:e.target.checked?[...f.memberKeys,t.key]:f.memberKeys.filter(k=>k!==t.key)})}/>{t.label}</label>)}
 {f.memberKeys.filter(k=>!targets.some(t=>t.key===k)).map(k=><p key={k}>Historical selector retained (not in current inputs): {k}</p>)}<button type="button" onClick={()=>onChange({...c,families:c.families.filter((_,n)=>n!==i)})}>Remove family</button></fieldset>;})}
 <button type="button" disabled={disabled} onClick={()=>onChange({...c,families:[...c.families,{id:crypto.randomUUID(),name:'',active:true,category:'DRILLING',unit:'hole',memberKeys:[],rate:null,evidence:''}]})}>Add price family</button></details>
 <details><summary>Future workstation configuration</summary><p>Configuration only; no machine amortization or workstation charge is calculated.</p>{c.workstations.map((w,i)=>{const patch=(v:Partial<WorkstationCostPlaceholder>)=>onChange({...c,workstations:c.workstations.map((x,n)=>n===i?{...x,...v}:x)});return <fieldset key={i}><legend>Workstation {i+1}</legend>{field('Workstation name',w.name,v=>patch({name:v??''}))}{stationFields.map((key,n)=><div key={key}>{field(stationLabels[n],w[key],v=>patch({[key]:v}))}</div>)}<button type="button" onClick={()=>onChange({...c,workstations:c.workstations.filter((_,n)=>n!==i)})}>Remove workstation</button></fieldset>;})}<button type="button" disabled={disabled} onClick={()=>onChange({...c,workstations:[...c.workstations,{name:'',purchaseCost:null,usefulLifeYears:null,productiveHoursPerYear:null,laborPerHour:null,energyPerHour:null,toolingPerHour:null,maintenancePerYear:null,allocatedOverheadPerYear:null}]})}>Add workstation placeholder</button></details>
 <p>Reserved future sources: supplier / historical prices. Reserved future costs: engineering, labor, assembly, installation, transport, external services, overhead. None contribute a calculated amount.</p></div>;
}
