'use client';
import {useEffect,useState} from 'react';
import {api} from './api';
import {paymentTriggers,type Milestone} from '../../../packages/contracts/payments';
import {money} from '../../../packages/modules/costing/decimal';
import type {state} from '../../../packages/modules/payments/service';
type State=Awaited<ReturnType<typeof state>>;
type Draft=Omit<Milestone,'amount'|'amountExact'|'currency'>;
const draft=(m:Milestone):Draft=>({id:m.id,title:m.title,description:m.description,basis:m.basis,value:m.value,trigger:m.trigger,requiredForProduction:m.requiredForProduction,visible:m.visible,internalNotes:m.internalNotes,customerNotes:m.customerNotes});
export function Payments({projectId}:{projectId:string}){
 const [quotes,setQuotes]=useState<{id:string;number:number;versionNumber:number;title:string}[]>([]),[quoteId,setQuoteId]=useState(''),[error,setError]=useState('');
 useEffect(()=>{api<typeof quotes>(`/projects/${projectId}/payment-quotes`).then(q=>{setQuotes(q);setQuoteId(q[0]?.id??'');}).catch(e=>setError(e.message));},[projectId]);
 return <section className="panel padded presentation-editor payments"><h2>Payments / Payment Plan</h2>{error&&<p role="alert">{error}</p>}<label>Payment quote context<select value={quoteId} onChange={e=>setQuoteId(e.target.value)}>{quotes.map(q=><option key={q.id} value={q.id}>V{q.versionNumber} · Quote {q.number} · {q.title}</option>)}</select></label>{quoteId?<PaymentContext key={quoteId} projectId={projectId} quoteId={quoteId}/>:<p>Create a complete quote to configure its payment plan.</p>}</section>;
}
function PaymentContext({projectId,quoteId}:{projectId:string;quoteId:string}){
 const [data,setData]=useState<State>(),[milestones,setMilestones]=useState<Draft[]>([]),[reason,setReason]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('');const base=`/projects/${projectId}`,url=`${base}/quotes/${quoteId}/payments`;
 function load(d:State){setData(d);setMilestones(d.history[0]?.plan.milestones.map(draft)??[]);setSelected(d.history[0]?.plan.id??'');}
 useEffect(()=>{api<State>(url).then(load).catch(e=>setError(e.message));},[url]);
 async function command(path:string,body:unknown){setBusy(true);setError('');setNotice('');try{await api(path,{method:'POST',body:JSON.stringify(body)});load(await api<State>(url));setNotice('Payment history saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const current=data?.history[0],chosen=data?.history.find(h=>h.plan.id===selected),isCurrent=chosen?.plan.id===current?.plan.id;
 if(!data)return <p role={error?'alert':undefined}>{error||'Loading payments…'}</p>;
 return <>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<p>Quote total: <strong>{data.quoteTotal===null?'INCOMPLETE':money(data.quoteTotal)} {data.currency}</strong></p><p>CLIENT_APPROVED: <strong>{data.clientApproved?'Yes':'No'}</strong>{data.approvalSuperseded?' · historical approval superseded':''}</p><p>PAYMENT_CONDITION_SATISFIED: <strong>{data.paymentCondition.satisfied?'Yes':'No'}</strong> · {data.paymentCondition.reason}</p><p>This is a payment prerequisite only, not Production Release authorization. Due triggers are metadata; installation and release are not executed here.</p>
 {data.canConfigure&&<details><summary>Configure new payment plan revision</summary><fieldset disabled={busy}><legend>Exact quote payment obligations</legend><p>Percentages use this quote total including VAT. No default advance is imposed. New revisions start with no transferred payments; historical reports remain on their original plan.</p>{milestones.map((m,i)=>{const patch=(p:Partial<Draft>)=>setMilestones(ms=>ms.map(x=>x.id===m.id?{...x,...p}:x));return <fieldset key={m.id}><legend>Milestone {i+1}</legend><label>Milestone title<input value={m.title} onChange={e=>patch({title:e.target.value})}/></label><label>Customer description<textarea value={m.description} onChange={e=>patch({description:e.target.value})}/></label><label>Amount basis<select value={m.basis} onChange={e=>patch({basis:e.target.value as Draft['basis']})}><option value="PERCENT">Percentage of quote including VAT</option><option value="FIXED">Fixed amount</option></select></label><label>Milestone value<input inputMode="decimal" value={m.value} onChange={e=>patch({value:e.target.value})}/></label><label>Due trigger<select value={m.trigger} onChange={e=>patch({trigger:e.target.value as Draft['trigger']})}>{paymentTriggers.map(t=><option key={t}>{t}</option>)}</select></label><label><input type="checkbox" checked={m.requiredForProduction} onChange={e=>patch({requiredForProduction:e.target.checked})}/>Required for future Production Release</label><label><input type="checkbox" checked={m.visible} onChange={e=>patch({visible:e.target.checked})}/>Customer visible</label><label>Milestone internal notes<textarea value={m.internalNotes} onChange={e=>patch({internalNotes:e.target.value})}/></label><label>Milestone customer notes<textarea value={m.customerNotes} onChange={e=>patch({customerNotes:e.target.value})}/></label><button disabled={!i} onClick={()=>setMilestones(ms=>{const n=[...ms];[n[i-1],n[i]]=[n[i],n[i-1]];return n;})}>Move milestone up</button><button disabled={i===milestones.length-1} onClick={()=>setMilestones(ms=>{const n=[...ms];[n[i+1],n[i]]=[n[i],n[i+1]];return n;})}>Move milestone down</button><button onClick={()=>setMilestones(ms=>ms.filter(x=>x.id!==m.id))}>Remove milestone</button></fieldset>;})}<button onClick={()=>setMilestones(ms=>[...ms,{id:crypto.randomUUID(),title:'',description:'',basis:'FIXED',value:'',trigger:'MANUAL_CUSTOM',requiredForProduction:false,visible:false,internalNotes:'',customerNotes:''}])}>Add milestone</button><label>Plan revision reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!milestones.length||!reason.trim()} onClick={()=>void command(`${base}/quotes/${quoteId}/payment-plans`,{requestId:crypto.randomUUID(),previousId:current?.plan.id??null,reason,milestones})}>Save payment plan revision</button></fieldset></details>}
 {data.history.length>0&&<><label>Payment plan history<select value={selected} onChange={e=>setSelected(e.target.value)}>{data.history.map(h=><option key={h.plan.id} value={h.plan.id}>Plan {h.plan.number}{h.plan.id===current?.plan.id?' · current':' · historical'}</option>)}</select></label>{chosen&&<><p>Plan {chosen.plan.number}: {chosen.plan.reason} · {new Date(chosen.plan.createdAt).toLocaleString()} · recorded by {chosen.plan.createdBy}</p><p>Configured milestones total: {money(chosen.configuredTotal)} {data.currency}. Quote total: {data.quoteTotal===null?'Not configured':money(data.quoteTotal)} {data.currency}. The schedule may cover only part of the quote; differences are not silently adjusted.</p>{chosen.milestones.map(m=><article className="payment-milestone" key={m.id}><h3>{m.title}</h3><p>{m.description}</p><p>Amount: {money(m.amount)} {m.currency} · Confirmed: {money(m.confirmedAmount)} · Outstanding: {money(m.outstandingAmount)} · Unconfirmed reports: {money(m.reportedAmount)}</p><strong>{m.status}</strong><p>{m.trigger} · Production payment prerequisite: {m.requiredForProduction?'Required':'Not required'} · Customer visible: {m.visible?'Yes':'No'}</p><p>Customer notes: {m.customerNotes||'—'}</p><p>Internal notes: {m.internalNotes||'—'}</p></article>)}{isCurrent&&data.canRecord&&<ReportForm key={chosen.plan.id} data={data} chosen={chosen} busy={busy} submit={body=>command(`${base}/payment-plans/${chosen.plan.id}/reports`,body)}/>}
 {chosen.reports.map(r=><PaymentRecord key={r.id} record={r} evidenceVisible={data.evidenceOptions.some(f=>f.id===r.evidenceSourceId)} events={chosen.events.filter(e=>e.paymentId===r.id)} canConfirm={!!isCurrent&&data.canConfirm} canReverse={data.canReverse} busy={busy} submit={body=>command(`${base}/payments/${r.id}/events`,body)}/>)}{!chosen.reports.length&&<p>No payment reported or confirmed for this plan.</p>}</>}</>}
 </>;
}
function ReportForm({data,chosen,busy,submit}:{data:State;chosen:State['history'][number];busy:boolean;submit:(body:unknown)=>Promise<void>}){
 const [milestoneId,setMilestoneId]=useState(chosen.milestones[0]?.id??''),[amount,setAmount]=useState(''),[paymentDate,setDate]=useState(''),[method,setMethod]=useState(''),[reference,setReference]=useState(''),[evidence,setEvidence]=useState(''),[note,setNote]=useState('');
 return <details><summary>Report payment</summary><fieldset disabled={busy}><legend>Unconfirmed payment evidence</legend><label>Payment milestone<select value={milestoneId} onChange={e=>setMilestoneId(e.target.value)}>{chosen.milestones.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>Reported amount ({data.currency})<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Payment date<input type="date" value={paymentDate} onChange={e=>setDate(e.target.value)}/></label><label>Payment method<input value={method} onChange={e=>setMethod(e.target.value)}/></label><label>Payment reference<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Existing version document evidence<select value={evidence} onChange={e=>setEvidence(e.target.value)}><option value="">No attached document</option>{data.evidenceOptions.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Payment internal note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={!amount||!paymentDate||!method.trim()} onClick={()=>void submit({requestId:crypto.randomUUID(),milestoneId,amount,paymentDate,method,reference,evidenceSourceId:evidence||null,internalNote:note})}>Record reported payment</button><p>Recording does not confirm receipt or satisfy a milestone.</p></fieldset></details>;
}
function PaymentRecord({record:r,evidenceVisible,events,canConfirm,canReverse,busy,submit}:{evidenceVisible:boolean;record:State['history'][number]['reports'][number];events:State['history'][number]['events'];canConfirm:boolean;canReverse:boolean;busy:boolean;submit:(body:unknown)=>Promise<void>}){
 const [reason,setReason]=useState(''),confirmed=events.some(e=>e.action==='CONFIRMED'),reversed=events.some(e=>e.action==='REVERSED');return <article className="payment-record"><h4>{money(r.amount)} {r.currency} · {reversed?'REVERSED':confirmed?'PAYMENT_CONFIRMED':'PAYMENT_REPORTED'}</h4><p>{r.paymentDate} · {r.method} · Reference: {r.reference||'—'}</p><p>Recorded by {r.createdBy} · {new Date(r.createdAt).toLocaleString()}</p><p>Internal note: {r.internalNote||'—'} · Evidence source: {r.evidenceSourceId||'None'}</p>{evidenceVisible&&r.evidenceSourceId&&<a className="button secondary" href={`/api/documents/${r.evidenceSourceId}/download`}>Download evidence</a>}{events.map(e=><p key={e.id}>{e.action} by {e.createdBy} · {new Date(e.createdAt).toLocaleString()} · {e.reason}</p>)}{(!confirmed&&canConfirm||confirmed&&!reversed&&canReverse)&&<><label>Confirmation / reversal reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()} onClick={()=>void submit({requestId:crypto.randomUUID(),action:confirmed?'REVERSED':'CONFIRMED',reason})}>{confirmed?'Reverse confirmed payment':'Confirm reported payment'}</button></>}</article>;
}
