'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {api} from './api';
import {itemKinds,mediaKinds,visibilityModes,type PresentationContent,type PresentationState,type MediaKind} from '../../../packages/contracts/presentation';
import {mediaLabel} from './presentation-preview';
const empty=():PresentationContent=>({title:'',description:'',sections:[],items:[],media:[],coverAssetId:null});
const visibilityLabel={INTERNAL_ONLY:'Internal only',CLIENT_PRESENTATION:'Visible in client presentation',DESIGN_DELIVERABLE_FUTURE:'Design deliverable — future access (not visible)'};
function move<T>(items:T[],index:number,step:number){const next=[...items];[next[index],next[index+step]]=[next[index+step],next[index]];return next;}
export function PresentationEditor({projectId,versions}:{projectId:string;versions:{id:string;number:number}[]}){
 const [versionId,setVersionId]=useState(versions[0]?.id??'');
 return <section className="panel padded presentation-editor"><h2>Client presentation</h2><p>Curate customer-facing content for an exact project version. Saving creates a new immutable presentation revision; no approval or publication is performed.</p>{versions.length?<><label>Presentation project version<select value={versionId} onChange={e=>setVersionId(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>V{v.number}</option>)}</select></label><VersionEditor key={versionId} projectId={projectId} versionId={versionId}/></>:<p>Create a project version first.</p>}</section>;
}
function VersionEditor({projectId,versionId}:{projectId:string;versionId:string}){
 const [state,setState]=useState<PresentationState>(),[content,setContent]=useState<PresentationContent>(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[kind,setKind]=useState<MediaKind>('RENDER'),[provenance,setProvenance]=useState('');
 const url=`/projects/${projectId}/versions/${versionId}/presentations`;
 useEffect(()=>{let active=true;api<PresentationState>(url).then(s=>{if(active){setState(s);setContent(s.revisions[0]?.content??empty());}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[url]);
 function edit(next:PresentationContent){setContent(next);setDirty(true);setNotice('');}
 async function save(){setBusy(true);setError('');try{await api(url,{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID(),previousId:state?.revisions[0]?.id??null,content})});const next=await api<PresentationState>(url);setState(next);setContent(next.revisions[0].content);setDirty(false);setNotice('Presentation revision saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{const data=new FormData(form);const uploaded=await api<{id:string}>(`${url}/media?${new URLSearchParams({kind,provenance})}`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:data});setState(await api<PresentationState>(url));edit({...content,media:[...content.media,{assetId:uploaded.id,sectionId:null,caption:'',visibility:'INTERNAL_ONLY'}]});setNotice('Image preserved privately. Choose visibility and save a revision to include it.');form.reset();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visibility=(value:typeof visibilityModes[number],label:string,change:(v:typeof value)=>void)=><label>{label}<select value={value} onChange={e=>change(e.target.value as typeof value)}>{visibilityModes.map(v=><option key={v} value={v}>{visibilityLabel[v]}</option>)}</select></label>;
 const section=(value:string|null,change:(v:string|null)=>void)=><label>Room / section<select value={value??''} onChange={e=>change(e.target.value||null)}><option value="">Whole project</option>{content.sections.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>;
 const order=(index:number,length:number,onMove:(step:number)=>void)=><div className="row"><button type="button" disabled={index===0||busy} onClick={()=>onMove(-1)}>Move up</button><button type="button" disabled={index===length-1||busy} onClick={()=>onMove(1)}>Move down</button></div>;
 if(!state)return <p role={error?'alert':undefined}>{error||'Loading presentation editor…'}</p>;
 return <>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<fieldset disabled={busy} className="presentation-fields"><legend>Customer-facing content</legend><label>Presentation title<input value={content.title} maxLength={200} onChange={e=>edit({...content,title:e.target.value})}/></label><label>Customer-facing project description<textarea value={content.description} maxLength={4000} onChange={e=>edit({...content,description:e.target.value})}/></label>
 <details><summary>Rooms / zones / sections ({content.sections.length})</summary>{content.sections.map((s,i)=>{const patch=(v:Partial<typeof s>)=>edit({...content,sections:content.sections.map(x=>x.id===s.id?{...x,...v}:x)});return <fieldset key={s.id}><legend>Section {i+1}</legend><label>Section title<input value={s.title} onChange={e=>patch({title:e.target.value})}/></label><label>Section description<textarea value={s.description} onChange={e=>patch({description:e.target.value})}/></label>{visibility(s.visibility,'Section visibility',v=>patch({visibility:v}))}{order(i,content.sections.length,step=>edit({...content,sections:move(content.sections,i,step)}))}<button type="button" disabled={content.items.some(x=>x.sectionId===s.id)||content.media.some(x=>x.sectionId===s.id)} onClick={()=>edit({...content,sections:content.sections.filter(x=>x.id!==s.id)})}>Remove empty section</button></fieldset>;})}<button type="button" onClick={()=>edit({...content,sections:[...content.sections,{id:crypto.randomUUID(),title:'',description:'',visibility:'INTERNAL_ONLY'}]})}>Add section</button></details>
 <details open><summary>Furniture, finishes, accessories and services ({content.items.length})</summary>{content.items.map((item,i)=>{const patch=(v:Partial<typeof item>)=>edit({...content,items:content.items.map(x=>x.id===item.id?{...x,...v}:x)});const refs=state.references.filter(r=>r.kind===item.kind);return <fieldset key={item.id}><legend>Presentation item {i+1}</legend><label>Item kind<select value={item.kind} onChange={e=>patch({kind:e.target.value as typeof item.kind,reference:null})}>{itemKinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Customer-facing item title<input value={item.title} maxLength={200} onChange={e=>patch({title:e.target.value})}/></label><label>Customer-facing item description<textarea value={item.description} maxLength={4000} onChange={e=>patch({description:e.target.value})}/></label>{section(item.sectionId,v=>patch({sectionId:v}))}{visibility(item.visibility,'Item visibility',v=>patch({visibility:v}))}
 {['MATERIAL','HARDWARE'].includes(item.kind)&&<label>Internal technical reference (not shown to client)<select value={item.reference?JSON.stringify(item.reference):''} onChange={e=>patch({reference:e.target.value?JSON.parse(e.target.value):null})}><option value="">No technical reference</option>{refs.map((r,n)=>{const ref=r.kind==='MATERIAL'?{kind:r.kind,materialMasterId:r.materialMasterId}:{kind:r.kind,reportId:r.reportId,itemIndex:r.itemIndex};return <option key={n} value={JSON.stringify(ref)}>{r.label}</option>;})}</select></label>}
 {item.kind==='SERVICE'&&<p>Examples: design, site measurement, travel, delivery, installation. Descriptive only; no price or service calculation.</p>}{order(i,content.items.length,step=>edit({...content,items:move(content.items,i,step)}))}<button type="button" onClick={()=>edit({...content,items:content.items.filter(x=>x.id!==item.id)})}>Remove item</button></fieldset>;})}<button type="button" onClick={()=>edit({...content,items:[...content.items,{id:crypto.randomUUID(),kind:'FURNITURE',title:'',description:'',sectionId:null,visibility:'INTERNAL_ONLY',reference:null}]})}>Add presentation item</button></details>
 <details open><summary>Images / renders ({content.media.length})</summary>{content.media.map((m,i)=>{const asset=state.assets.find(a=>a.id===m.assetId)!;const patch=(v:Partial<typeof m>)=>edit({...content,media:content.media.map(x=>x.assetId===m.assetId?{...x,...v}:x),coverAssetId:v.visibility&&v.visibility!=='CLIENT_PRESENTATION'&&content.coverAssetId===m.assetId?null:content.coverAssetId});return <fieldset key={m.assetId}><legend>Image {i+1} · {mediaLabel[asset.kind]}</legend><img className="presentation-thumb" src={`/api${url}/media/${asset.id}`} alt={m.caption||mediaLabel[asset.kind]}/><label>Customer-facing caption<input value={m.caption} maxLength={1000} onChange={e=>patch({caption:e.target.value})}/></label>{section(m.sectionId,v=>patch({sectionId:v}))}{visibility(m.visibility,'Image visibility',v=>patch({visibility:v}))}<label><input type="radio" name="cover" checked={content.coverAssetId===m.assetId} disabled={m.visibility!=='CLIENT_PRESENTATION'} onChange={()=>edit({...content,coverAssetId:m.assetId})}/>Use as cover</label>{order(i,content.media.length,step=>edit({...content,media:move(content.media,i,step)}))}<button type="button" onClick={()=>edit({...content,media:content.media.filter(x=>x.assetId!==m.assetId),coverAssetId:content.coverAssetId===m.assetId?null:content.coverAssetId})}>Detach image</button><details><summary>Internal media provenance</summary><p>{asset.name} · {asset.provenance||'No additional provenance supplied'} · SHA-256 {asset.hash}</p></details></fieldset>;})}<button type="button" onClick={()=>edit({...content,coverAssetId:null})}>Clear cover</button>
 {state.assets.filter(a=>!content.media.some(m=>m.assetId===a.id)).map(a=><p key={a.id}>{a.name} · {mediaLabel[a.kind]} <button type="button" onClick={()=>edit({...content,media:[...content.media,{assetId:a.id,sectionId:null,caption:'',visibility:'INTERNAL_ONLY'}]})}>Attach preserved image</button></p>)}</details>
 </fieldset><form onSubmit={upload} className="presentation-upload"><h3>Upload presentation image</h3><p>PNG / JPEG, up to 10 MB. Separate from manufacturing source files. New images start internal-only.</p><label>Media type<select value={kind} onChange={e=>setKind(e.target.value as MediaKind)}>{mediaKinds.map(k=><option key={k} value={k}>{mediaLabel[k]}</option>)}</select></label><label>Internal image provenance<input value={provenance} onChange={e=>setProvenance(e.target.value)} maxLength={1000}/></label><label>Presentation image file<input type="file" name="file" accept="image/png,image/jpeg" required/></label><button disabled={busy} className="button secondary">Upload presentation image</button></form>
 <div className="presentation-actions"><button className="button" disabled={busy||!content.title.trim()} onClick={()=>void save()}>Save presentation revision</button>{state.canPreview&&state.revisions[0]&&<a className="button secondary" target="_blank" rel="noopener noreferrer" href={`/presentation-preview/${projectId}/${versionId}/${state.revisions[0].id}`}>View as client</a>}</div>{dirty&&<p>Unsaved changes. Preview shows the last saved revision.</p>}
 <details><summary>Presentation history ({state.revisions.length})</summary>{state.revisions.map(r=><article key={r.id}><p>Revision {r.number} · {new Date(r.createdAt).toLocaleString()} · {r.content.title}</p><p>Content SHA-256 {r.contentHash}</p>{state.canPreview&&<a target="_blank" rel="noopener noreferrer" href={`/presentation-preview/${projectId}/${versionId}/${r.id}`}>Preview revision {r.number}</a>}</article>)}</details></>;
}
