'use client';
import {useEffect,useState} from 'react';
import {api} from './api';
import {quoteLineKinds,type QuoteContent,type QuoteState,type QuoteCalculation,type Adjustment} from '../../../packages/contracts/quote';
import {QuoteTotalsView,quoteMoney} from './quote-preview';
type Draft=Omit<QuoteContent,'currency'>&{currency:QuoteContent['currency']|''};
const none:Adjustment={kind:'NONE',value:null};
const empty=():Draft=>({title:'',currency:'',customerNotes:'',internalNotes:'',sections:[],lines:[],discount:none,vatPercent:null,deposit:none});
function move<T>(items:T[],index:number,step:number){const next=[...items];[next[index],next[index+step]]=[next[index+step],next[index]];return next;}
function AdjustmentEditor({label,value,onChange}:{label:string;value:Adjustment;onChange:(v:Adjustment)=>void}){
 return <div><label>{label} mode<select value={value.kind} onChange={e=>onChange(e.target.value==='NONE'?none:{kind:e.target.value as 'AMOUNT'|'PERCENT',value:''})}><option value="NONE">Not specified / none</option><option value="AMOUNT">Fixed amount</option><option value="PERCENT">Percentage</option></select></label>{value.kind!=='NONE'&&<label>{label} value<input inputMode="decimal" value={value.value} onChange={e=>onChange({...value,value:e.target.value})}/></label>}</div>;
}
export function QuoteBuilder({projectId,versions}:{projectId:string;versions:{id:string;number:number}[]}){
 const [versionId,setVersionId]=useState(versions[0]?.id??'');return <section className="panel padded presentation-editor quote-builder"><h2>Commercial quote</h2><p>Manual offered prices are independent of internal costing. Save an exact-version offer; every edit creates a new revision.</p>{versions.length?<><label>Quote project version<select value={versionId} onChange={e=>setVersionId(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>V{v.number}</option>)}</select></label><VersionQuote key={versionId} projectId={projectId} versionId={versionId}/></>:<p>Create a project version first.</p>}</section>;
}
function VersionQuote({projectId,versionId}:{projectId:string;versionId:string}){
 const [state,setState]=useState<QuoteState>(),[content,setContent]=useState<Draft>(empty),[presentationId,setPresentationId]=useState<string|null>(null),[result,setResult]=useState<QuoteCalculation>(),[calculationError,setCalculationError]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const url=`/projects/${projectId}/versions/${versionId}/quotes`;
 useEffect(()=>{let active=true;api<QuoteState>(url).then(s=>{if(active){setState(s);setContent(s.history[0]?.content??empty());setPresentationId(s.history[0]?.presentationRevisionId??null);setResult(s.history[0]?.result);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[url]);
 useEffect(()=>{if(!state?.canEdit)return;let active=true;setResult(undefined);setCalculationError('');if(!content.title.trim()||!content.currency)return;const timer=setTimeout(()=>{api<QuoteCalculation>(`${url}/calculate`,{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID(),previousId:state.history[0]?.id??null,presentationRevisionId:presentationId,content})}).then(r=>{if(active)setResult(r);}).catch(e=>{if(active)setCalculationError(e.message);});},400);return()=>{active=false;clearTimeout(timer);};},[content,presentationId,state,url]);
 function edit(c:Draft){setContent(c);setDirty(true);setNotice('');}
 async function save(){setBusy(true);setError('');try{await api(url,{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID(),previousId:state?.history[0]?.id??null,presentationRevisionId:presentationId,content})});const next=await api<QuoteState>(url);setState(next);setContent(next.history[0].content);setResult(next.history[0].result);setDirty(false);setNotice('Quote revision saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const order=(i:number,length:number,change:(step:number)=>void)=><div className="row"><button type="button" disabled={busy||i===0} onClick={()=>change(-1)}>Move up</button><button type="button" disabled={busy||i===length-1} onClick={()=>change(1)}>Move down</button></div>;
 const presentation=state?.presentations.find(p=>p.id===presentationId);
 if(!state)return <p role={error?'alert':undefined}>{error||'Loading quote builder…'}</p>;
 return <>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<fieldset className="presentation-fields" disabled={busy||!state.canEdit}><legend>Offered commercial content</legend><label>Quote title<input value={content.title} maxLength={200} onChange={e=>edit({...content,title:e.target.value})}/></label><label>Quote currency<select value={content.currency} onChange={e=>edit({...content,currency:e.target.value as Draft['currency']})}><option value="">Select currency</option><option>RON</option><option>EUR</option><option>USD</option></select></label><p>Amounts are explicit offers; changing currency does not convert them. Review every offered amount before saving.</p>
 <label>Exact presentation revision<select value={presentationId??''} onChange={e=>{setPresentationId(e.target.value||null);edit({...content,lines:content.lines.map(l=>({...l,presentationSectionId:null}))});}}><option value="">No presentation attached</option>{state.presentations.map(p=><option key={p.id} value={p.id}>Revision {p.number} · {p.title}</option>)}</select></label>
 <details><summary>Quote sections ({content.sections.length})</summary>{content.sections.map((s,i)=>{const patch=(v:Partial<typeof s>)=>edit({...content,sections:content.sections.map(x=>x.id===s.id?{...x,...v}:x)});return <fieldset key={s.id}><legend>Quote section {i+1}</legend><label>Section title<input value={s.title} onChange={e=>patch({title:e.target.value})}/></label><label>Section description<textarea value={s.description} onChange={e=>patch({description:e.target.value})}/></label><label><input type="checkbox" checked={s.visible} onChange={e=>patch({visible:e.target.checked})}/>Show section to customer</label>{order(i,content.sections.length,step=>edit({...content,sections:move(content.sections,i,step)}))}<button disabled={content.lines.some(l=>l.sectionId===s.id)} onClick={()=>edit({...content,sections:content.sections.filter(x=>x.id!==s.id)})}>Remove empty quote section</button></fieldset>;})}<button onClick={()=>edit({...content,sections:[...content.sections,{id:crypto.randomUUID(),title:'',description:'',visible:false}]})}>Add quote section</button></details>
 <details open><summary>Commercial lines ({content.lines.length})</summary>{content.lines.map((l,i)=>{const patch=(v:Partial<typeof l>)=>edit({...content,lines:content.lines.map(x=>x.id===l.id?{...x,...v}:x)}),calculation=result?.lines.find(x=>x.lineId===l.id);return <fieldset key={l.id}><legend>Quote line {i+1}</legend><label>Line type<select value={l.kind} onChange={e=>patch({kind:e.target.value as typeof l.kind})}>{quoteLineKinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Line title<input value={l.title} maxLength={200} onChange={e=>patch({title:e.target.value})}/></label><label>Line description<textarea value={l.description} onChange={e=>patch({description:e.target.value})}/></label><label>Quote section<select value={l.sectionId??''} onChange={e=>patch({sectionId:e.target.value||null})}><option value="">Whole quote</option>{content.sections.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>Presentation room reference<select value={l.presentationSectionId??''} disabled={!presentation} onChange={e=>patch({presentationSectionId:e.target.value||null})}><option value="">No room reference</option>{presentation?.sections.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>
 <label>Pricing mode<select value={l.pricingMode} onChange={e=>patch({pricingMode:e.target.value as typeof l.pricingMode,offeredUnitPrice:null,offeredLineTotal:null})}><option>MANUAL_PRICE</option><option>CALCULATED_PRICE</option></select></label>
 {l.pricingMode==='CALCULATED_PRICE'?<><p>Future pricing engine placeholder. No internal cost is used as a selling price.</p><label>Internal calculated-price reference<input value={l.calculatedPriceReference??''} onChange={e=>patch({calculatedPriceReference:e.target.value||null})}/></label></>:<><label>Offered price basis<select value={l.basis} onChange={e=>patch({basis:e.target.value as typeof l.basis,offeredUnitPrice:null,offeredLineTotal:null})}><option value="LINE_TOTAL">Manual line total</option><option value="UNIT_PRICE">Commercial quantity × unit price</option></select></label><label>{l.basis==='UNIT_PRICE'?'Offered unit price':'Offered line total'}<input inputMode="decimal" value={(l.basis==='UNIT_PRICE'?l.offeredUnitPrice:l.offeredLineTotal)??''} onChange={e=>patch(l.basis==='UNIT_PRICE'?{offeredUnitPrice:e.target.value||null}:{offeredLineTotal:e.target.value||null})}/></label></>}
 <label>Commercial quantity (optional for line total)<input inputMode="decimal" value={l.quantity??''} onChange={e=>patch({quantity:e.target.value||null})}/></label><label>Commercial unit<input value={l.unit} maxLength={40} onChange={e=>patch({unit:e.target.value})}/></label><AdjustmentEditor label="Line discount" value={l.discount} onChange={v=>patch({discount:v})}/><label>Customer line note<textarea value={l.customerNote} onChange={e=>patch({customerNote:e.target.value})}/></label><label>Internal line note<textarea value={l.internalNote} onChange={e=>patch({internalNote:e.target.value})}/></label><label><input type="checkbox" checked={l.visible} onChange={e=>patch({visible:e.target.checked})}/>Include line in customer quote and totals</label><p>Offered line total after discount: {calculation?.status==='PRICED'?`${quoteMoney(calculation.total)} ${content.currency}`:calculation?.status==='HIDDEN'?'Hidden / excluded':'PRICE PENDING'}</p>{order(i,content.lines.length,step=>edit({...content,lines:move(content.lines,i,step)}))}<button onClick={()=>edit({...content,lines:content.lines.filter(x=>x.id!==l.id)})}>Remove quote line</button></fieldset>;})}<button onClick={()=>edit({...content,lines:[...content.lines,{id:crypto.randomUUID(),kind:'FURNITURE',sectionId:null,presentationSectionId:null,title:'',description:'',customerNote:'',internalNote:'',visible:false,pricingMode:'MANUAL_PRICE',calculatedPriceReference:null,basis:'LINE_TOTAL',quantity:null,unit:'',offeredUnitPrice:null,offeredLineTotal:null,discount:none}]})}>Add quote line</button></details>
 <AdjustmentEditor label="Quote discount" value={content.discount} onChange={v=>edit({...content,discount:v})}/><label>VAT percentage<input value={content.vatPercent??''} inputMode="decimal" placeholder="Not configured" onChange={e=>edit({...content,vatPercent:e.target.value||null})}/></label><AdjustmentEditor label="Deposit" value={content.deposit} onChange={v=>edit({...content,deposit:v})}/><label>Customer commercial notes<textarea value={content.customerNotes} onChange={e=>edit({...content,customerNotes:e.target.value})}/></label><label>Internal quote notes<textarea value={content.internalNotes} onChange={e=>edit({...content,internalNotes:e.target.value})}/></label></fieldset>
 <p>Hidden sections/lines are excluded from all offered totals. Line discounts apply first, then the quote discount, then VAT. Deposit percentage uses total with VAT. No internal costing is required.</p>{calculationError&&<p role="alert">{calculationError}</p>}{result&&<><QuoteTotalsView totals={result.totals} currency={content.currency} deposit={content.deposit}/>{result.issues.map((x,i)=><p key={i}>{x}</p>)}</>}
 <div className="presentation-actions">{state.canEdit&&<button className="button" disabled={busy||!content.title.trim()||!content.currency} onClick={()=>void save()}>Save quote revision</button>}{state.canPreview&&state.history[0]&&<a className="button secondary" target="_blank" rel="noopener noreferrer" href={`/quote-preview/${projectId}/${versionId}/${state.history[0].id}`}>View quote as client</a>}</div>{dirty&&<p>Unsaved changes. Client preview uses the last saved quote.</p>}
 <details><summary>Quote history ({state.history.length})</summary>{state.history.map(q=><article key={q.id}><p>Quote {q.number} · {q.content.title} · {new Date(q.createdAt).toLocaleString()} · {q.result.status}</p><p>Offered total with VAT: {quoteMoney(q.result.totals.withVat)} {q.content.currency}</p>{state.canPreview&&<a target="_blank" rel="noopener noreferrer" href={`/quote-preview/${projectId}/${versionId}/${q.id}`}>Preview quote {q.number}</a>}</article>)}</details></>;
}
