'use client';
import { useEffect, useState } from 'react';
import { api } from './api';
import { MaterialResolution } from './material-resolution';
import type { Source, Version } from '../../../packages/contracts/index';
import type { TechnicalModel, TechnicalModelDetail } from '../../../packages/contracts/technical-model';

export function TechnicalModelView({ projectId, sources, versions, onChanged }: { projectId: string; sources: Source[]; versions: Version[]; onChanged: () => void }) {
  const [models, setModels] = useState<TechnicalModel[]>([]), [detail, setDetail] = useState<TechnicalModelDetail>();
  const [cabinetReportId, setCabinetReportId] = useState(''), [partReportId, setPartReportId] = useState('');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [requestId, setRequestId] = useState('');
  const [section, setSection] = useState('Cabinets'), [page, setPage] = useState(0), [cabinetFilter, setCabinetFilter] = useState('');
  useEffect(() => { let active = true; api<TechnicalModel[]>(`/projects/${projectId}/technical-models`).then(async rows => { if (!active) return; setModels(rows); if (rows[0]) { const data = await api<TechnicalModelDetail>(`/projects/${projectId}/technical-models/${rows[0].id}`); if (active) setDetail(data); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [projectId]);
  const options = (profile: string) => sources.flatMap(source => source.csvAttempts.filter(a => a.profile === profile && a.status === 'NEEDS_REVIEW').map(a => <option key={a.id} value={a.id}>{source.name} · V{versions.find(v => v.id === source.versionId)?.number} · {new Date(a.createdAt).toLocaleString()} · {a.id.slice(0, 8)}</option>));
  async function open(id: string) { setBusy(true); setError(''); try { setDetail(await api<TechnicalModelDetail>(`/projects/${projectId}/technical-models/${id}`)); setPage(0); setCabinetFilter(''); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function create() {
    setBusy(true); setError(''); const key = requestId || crypto.randomUUID(); setRequestId(key);
    try {
      const result = await api<{ id: string }>(`/projects/${projectId}/technical-models`, { method: 'POST', body: JSON.stringify({ cabinetReportId, partReportId, requestId: key }) });
      setModels(await api<TechnicalModel[]>(`/projects/${projectId}/technical-models`)); await open(result.id); setRequestId(''); onChanged();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  const filtered = detail?.parts.filter(p => !cabinetFilter || (cabinetFilter === 'unlinked' ? !p.cabinetId : p.cabinetId === cabinetFilter)) ?? [];
  const pages = section === 'Parts' ? Math.ceil(filtered.length / 25) : section === 'Cabinets' ? Math.ceil((detail?.cabinets.length ?? 0) / 25) : section === 'Materials' ? Math.ceil((detail?.materials.length ?? 0) / 25) : Math.ceil((detail?.model.issues.length ?? 0) / 25);
  return <section className="panel padded technical-review"><h2>Technical model</h2><p>Combine two existing reports from the same source version. This creates a new immutable review version; it does not approve or authorize manufacturing.</p>
    <details><summary>Create from CSV reports</summary><div className="form-grid"><label>Cabinet import report<select value={cabinetReportId} disabled={busy} onChange={e => { setCabinetReportId(e.target.value); setRequestId(''); }}><option value="">Choose a successful cabinet report</option>{options('polyboard-cabinets-7/v1')}</select></label><label>Cutting import report<select value={partReportId} disabled={busy} onChange={e => { setPartReportId(e.target.value); setRequestId(''); }}><option value="">Choose a successful cutting report</option>{options('polyboard-cutting-18/v1')}</select></label></div><button className="button" disabled={busy || !cabinetReportId || !partReportId} onClick={create}>{busy ? 'Building model…' : 'Create review version'}</button><p className="helper">The same report pair reopens its existing model without creating duplicate versions.</p></details>
    {error && <div role="alert" className="error">{error}</div>}
    {models.length > 0 && <label>Normalized version<select disabled={busy} value={detail?.model.id ?? ''} onChange={e => void open(e.target.value)}><option value="" disabled>Select model</option>{models.map(m => <option key={m.id} value={m.id}>V{m.versionNumber} · {m.summary.cabinets} cabinets / {m.summary.partRows} rows / {m.summary.units} units · Needs review</option>)}</select></label>}
    {!detail && !error && <p>No normalized model selected. Choose the two existing reports above.</p>}
    {detail && <><h3>V{detail.model.versionNumber} · Technical review</h3><p className="model-totals">{detail.model.summary.cabinets} cabinets · {detail.model.summary.partRows} part rows · {detail.model.summary.units} units · {detail.model.summary.materials} materials</p><p>{detail.model.summary.linkedRows} linked rows · {detail.model.summary.ambiguousRows} ambiguous · {detail.model.summary.unmappedRows} unmapped</p>
      <MaterialResolution key={detail.model.id} projectId={projectId} modelId={detail.model.id} /><details><summary>Model provenance</summary><p>Model: {detail.model.id}<br />Normalizer: {detail.model.normalizer}<br />Source version: {detail.model.baseVersionId}<br />Created: {new Date(detail.model.createdAt).toLocaleString()} · {detail.model.createdBy}</p><p>Cabinet report: {detail.model.cabinetReportId}<br />Cutting report: {detail.model.partReportId}</p>{detail.sources.map(s => <p key={s.id}>{s.name}<br /><code className="hash">{s.hash}</code></p>)}</details>
      <div className="tabs" role="tablist" aria-label="Technical model sections">{['Cabinets', 'Parts', 'Materials', 'Import issues / unmapped data'].map(label => <button key={label} role="tab" aria-selected={section === label} className={section === label ? 'selected' : ''} onClick={() => { setSection(label); setPage(0); }}>{label}</button>)}</div>
      {section === 'Cabinets' && <div className="table-wrap"><table><thead><tr><th>Cabinet</th><th>Qty</th><th>Height × width × depth (mm)</th><th>Linked rows / units</th><th>Source row</th></tr></thead><tbody>{detail.cabinets.slice(page * 25, (page + 1) * 25).map(c => { const rows = detail.parts.filter(p => p.cabinetId === c.id); return <tr key={c.id}><td><button className="button secondary" onClick={() => { setCabinetFilter(c.id); setSection('Parts'); setPage(0); }}>{c.name}</button></td><td>{c.quantity}</td><td>{c.dimensions.height} × {c.dimensions.width} × {c.dimensions.depth}</td><td>{rows.length} / {rows.reduce((n, p) => n + p.data.quantity, 0)}</td><td>{c.sourceRow} · line {c.sourceLine}</td></tr>; })}</tbody></table></div>}
      {section === 'Parts' && <><label>Filter parts by cabinet<select value={cabinetFilter} onChange={e => { setCabinetFilter(e.target.value); setPage(0); }}><option value="">All parts</option><option value="unlinked">Ambiguous / unmapped only</option>{detail.cabinets.map(c => <option key={c.id} value={c.id}>{c.name} · row {c.sourceRow}</option>)}</select></label><div className="table-wrap"><table><thead><tr><th>Part / reference</th><th>Cabinet link</th><th>Dimensions (mm)</th><th>Qty</th><th>Material / thickness</th><th>Source / raw data</th></tr></thead><tbody>{filtered.slice(page * 25, (page + 1) * 25).map(p => { const material = detail.materials.find(m => m.id === p.materialId)!; return <tr key={p.id}><td>{p.data.name}<br />#{p.data.sourceNumber}</td><td>{p.cabinetId ? detail.cabinets.find(c => c.id === p.cabinetId)?.name : p.linkStatus}<br /><small>Source label: {p.data.cabinetLabel}</small></td><td>{p.data.dimensions.first} × {p.data.dimensions.second}<br /><small>Source order; no axis inference</small></td><td>{p.data.quantity}</td><td>{material.description}<br />{material.thickness} mm</td><td>Row {p.sourceRow} · line {p.sourceLine}<details><summary>Raw / provenance</summary><p>Source: {p.sourceId}<br />Report: {p.reportId}<br />Column 10 (unmapped): {p.data.unmapped.column10}</p><ul>{detail.edges.filter(e => e.partId === p.id).map(e => <li key={e.slot}>Slot {e.slot}: {e.material || '(empty)'} / {e.thickness || '(empty)'} mm · side unmapped</li>)}</ul><ol>{p.data.raw.map((v, i) => <li key={i}><code>{v || '(empty)'}</code></li>)}</ol></details></td></tr>; })}</tbody></table></div>{!filtered.length && <p>No parts in this selection.</p>}</>}
      {section === 'Materials' && <div className="table-wrap"><table><thead><tr><th>Material</th><th>Thickness (mm)</th><th>Part rows / units</th><th>Identity</th></tr></thead><tbody>{detail.materials.slice(page * 25, (page + 1) * 25).map(m => { const rows = detail.parts.filter(p => p.materialId === m.id); return <tr key={m.id}><td>{m.description}</td><td>{m.thickness}</td><td>{rows.length} / {rows.reduce((n, p) => n + p.data.quantity, 0)}</td><td><small>{m.id}<br />Version-specific; resolution recorded separately</small></td></tr>; })}</tbody></table></div>}
      {section === 'Import issues / unmapped data' && <><p>Column 10 is unmapped on every part. Four raw edge slots are retained per row, including empty slots; none has an assigned side. Cabinet price fields remain in the protected source report.</p><ul>{detail.model.issues.slice(page * 25, (page + 1) * 25).map((issue, i) => <li key={i}><strong>{issue.code}{issue.row ? ` · ${issue.entity} row ${issue.row}` : ''}</strong><p>{issue.message}</p></li>)}</ul><button className="button secondary" onClick={() => { setCabinetFilter('unlinked'); setSection('Parts'); setPage(0); }}>Show ambiguous / unmapped parts</button></>}
      <div className="csv-pagination"><button className="button secondary" disabled={!page} onClick={() => setPage(p => p - 1)}>Previous</button><span>Page {page + 1} / {Math.max(1, pages)}</span><button className="button secondary" disabled={page + 1 >= pages} onClick={() => setPage(p => p + 1)}>Next</button></div>
    </>}
  </section>;
}
