'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { LayoutDashboard, Users, FolderKanban, Factory, ShoppingCart, Package, Files, Settings, ArrowUpRight, Plus, ArrowLeft, LogOut, Menu, X, ChevronRight, FileUp, LockKeyhole, Layers, Clock3, CircleCheck, Search, Armchair } from 'lucide-react';
import { api } from './api';
import { CsvImport } from './csv-import';
import { TechnicalModelView } from './technical-model';
import { MaterialLibrary } from './material-library';
import type { Customer, Project, ProjectDetail, Identity, Source } from '../../../packages/contracts/index';

const navigation = [
  { href: '/', label: 'Overview', icon: LayoutDashboard }, { href: '/customers', label: 'Customers', icon: Users },
  { href: '/projects', label: 'Projects', icon: FolderKanban }, { href: '/production', label: 'Production', icon: Factory },
  { href: '/purchasing', label: 'Purchasing', icon: ShoppingCart }, { href: '/inventory', label: 'Inventory', icon: Package },
  { href: '/documents', label: 'Documents', icon: Files }, { href: '/library', label: 'Material Library', icon: Layers }, { href: '/settings', label: 'Settings', icon: Settings }
];
const date = (value: string) => new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
const code = (id: string) => `MLX-${id.slice(0, 8).toUpperCase()}`;
function useResource<T>(path: string) {
  const [data, setData] = useState<T>(); const [error, setError] = useState(''); const [revision, setRevision] = useState(0);
  useEffect(() => { let active = true; setError(''); api<T>(path).then(value => { if (active) setData(value); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [path, revision]);
  return { data, error, reload: () => setRevision(n => n + 1) };
}
function ErrorMessage({ text }: { text: string }) { return text ? <div role="alert" className="error">{text}</div> : null; }
function Pending({ error }: { error: string }) { return error ? <ErrorMessage text={error} /> : <div className="loading" role="status">Loading your workspace…</div>; }
function Heading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function Empty({ title, children }: { title: string; children: ReactNode }) { return <div className="empty"><div className="empty-icon"><FolderKanban size={26} /></div><h3>{title}</h3><div className="empty-copy">{children}</div></div>; }
function Badge({ children }: { children: ReactNode }) { return <span className="badge">{children}</span>; }
function ProjectCards({ items }: { items: Project[] }) { return items.length ? <div className="project-grid">{items.map(p => <Link className="project-card" href={`/projects/${p.id}`} key={p.id}><div className="row"><span className="project-icon"><Armchair size={24} /></span><ArrowUpRight size={18} /></div><span className="mono">{code(p.id)}</span><h3>{p.name}</h3><p>{p.description || 'Start with a version and preserve your project source files.'}</p><footer><Badge>Design preparation</Badge><span>{date(p.createdAt)}</span></footer></Link>)}</div> : <Empty title="Your next project starts here">Create a customer, then bring their project into one place.</Empty>; }

export function Workspace() {
  const path = usePathname(); const router = useRouter(); const [identity, setIdentity] = useState<Identity>(); const [menu, setMenu] = useState(false);
  useEffect(() => { if (path === '/login') return; api<Identity>('/me').then(setIdentity).catch(() => router.replace('/login')); }, [path, router]);
  if (path === '/login') return <Login onLogin={setIdentity} />;
  if (!identity) return <div className="loading">Opening MOBLUX OS…</div>;
  const section = navigation.find(n => n.href !== '/' && path.startsWith(n.href))?.label || 'Overview';
  let content: ReactNode;
  if (path === '/') content = <Dashboard />;
  else if (path === '/customers') content = <Customers />;
  else if (path === '/customers/new') content = <CustomerForm />;
  else if (path.startsWith('/customers/')) content = <CustomerDetail key={path} id={path.split('/')[2]} />;
  else if (path === '/projects') content = <Projects />;
  else if (path === '/projects/new') content = <ProjectForm />;
  else if (path.startsWith('/projects/')) content = <ProjectView key={path} id={path.split('/')[2]} />;
  else if (path === '/documents') content = <Documents />;
  else if (path === '/library') content = <MaterialLibrary />;
  else if (path === '/settings') content = <SettingsView identity={identity} />;
  else if (['/production', '/purchasing', '/inventory'].includes(path)) content = <ComingLater name={section} />;
  else content = <Empty title="Page not found"><Link href="/">Return to overview</Link></Empty>;
  return <div className="app"><aside className={`sidebar ${menu ? 'open' : ''}`}><Link className="brand" href="/"><span className="brand-mark">M</span><span>MOBLUX <b>OS</b></span></Link><button className="mobile-close icon-button" onClick={() => setMenu(false)} aria-label="Close navigation"><X /></button><div className="workspace-label">WORKSPACE <span>01</span></div><nav aria-label="Main navigation">{navigation.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setMenu(false)} className={(href === '/' ? path === '/' : path.startsWith(href)) ? 'active' : ''}><Icon size={19} />{label}{label === 'Projects' && <ChevronRight className="nav-arrow" size={16} />}</Link>)}</nav><div className="sidebar-note"><span className="live-dot" /> A foundation for better work<p>From the first conversation<br />to the final installation.</p></div><div className="profile"><span className="avatar">DA</span><div><strong>Development admin</strong><small>Local workspace</small></div><button aria-label="Sign out" className="icon-button" onClick={async () => { await api('/auth/logout', { method: 'POST' }); setIdentity(undefined); router.push('/login'); }}><LogOut size={17} /></button></div></aside>{menu && <button className="scrim" aria-label="Close navigation" onClick={() => setMenu(false)} />}<div className="main"><header className="topbar"><div className="row"><button className="mobile-toggle icon-button" onClick={() => setMenu(true)} aria-label="Open navigation"><Menu /></button><span className="muted">Workspace</span><ChevronRight size={14} /><strong>{section}</strong></div><span className="environment"><span className="live-dot" /> Local development</span></header><main key={path}>{content}</main><footer className="page-footer"><span>MOBLUX OS</span><span>Built around the way you work · v0.1</span></footer></div></div>;
}
function Login({ onLogin }: { onLogin: (user: Identity) => void }) {
  const router = useRouter(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const form = new FormData(e.currentTarget); try { await api('/auth/login', { method: 'POST', body: JSON.stringify({ code: form.get('code') }) }); onLogin(await api<Identity>('/me')); router.replace('/'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="login"><div className="login-story"><div className="brand"><span className="brand-mark">M</span>MOBLUX OS</div><div><span className="eyebrow">FROM IDEA TO INSTALLATION</span><h1>Good work starts<br />with a clear view.</h1><p>Your customers, projects and source files.<br />One connected workspace.</p></div><small>Furniture manufacturing, thoughtfully organized.</small></div><div className="login-panel"><form onSubmit={submit}><span className="empty-icon"><LockKeyhole /></span><h1>Welcome to MOBLUX.</h1><p>Sign in to your local development workspace.</p><ErrorMessage text={error} /><label>Development access code<input name="code" type="password" required autoComplete="current-password" placeholder="Enter your local access code" /></label><button disabled={busy} className="button full">{busy ? 'Signing in…' : 'Open workspace'}<ArrowUpRight size={18} /></button><p className="helper">Find <code>DEV_LOGIN_CODE</code> in your local <code>.env</code> file. This sign-in is for local development only.</p></form></div></div>;
}
function Dashboard() {
  const c = useResource<Customer[]>('/customers'), p = useResource<Project[]>('/projects'), d = useResource<Source[]>('/documents');
  if (!c.data || !p.data || !d.data) return <Pending error={c.error || p.error || d.error} />;
  return <><Heading eyebrow="YOUR WORKSPACE, AT A GLANCE" title="Make room for good work." description="A clear starting point for every customer and every project." action={<Link className="button" href="/projects/new"><Plus size={18} />New project</Link>} /><div className="stats">{[{ label: 'Customers', value: c.data.length, icon: Users, href: '/customers', note: 'Relationships in your workspace' }, { label: 'Projects', value: p.data.length, icon: FolderKanban, href: '/projects', note: 'From conversation to design' }, { label: 'Source files', value: d.data.length, icon: Files, href: '/documents', note: 'Originals and import reports' }].map(s => <Link href={s.href} className="stat" key={s.label}><div className="row"><span>{s.label}</span><s.icon size={20} /></div><strong>{s.value.toString().padStart(2, '0')}</strong><small>{s.note}</small></Link>)}</div><div className="section-heading"><div><h2>Recent projects</h2><p>Your latest work, all in one place.</p></div><Link href="/projects">View all projects <ArrowUpRight size={16} /></Link></div><ProjectCards items={p.data.slice(0, 4)} /><div className="getting-started"><div><span className="eyebrow">A SIMPLE START</span><h2>Build the project story.</h2><p>Keep the customer, each design version and the original source files connected.</p></div><ol><li><span>01</span>Add a customer</li><li><span>02</span>Create their project</li><li><span>03</span>Preserve a version & sources</li></ol></div></>;
}
function Customers() {
  const { data, error } = useResource<Customer[]>('/customers'); const [search, setSearch] = useState('');
  if (!data) return <Pending error={error} />;
  const items = data.filter(c => `${c.name} ${c.email}`.toLowerCase().includes(search.toLowerCase()));
  return <><Heading eyebrow="RELATIONSHIPS" title="Customers" description="The people behind every project." action={<Link href="/customers/new" className="button"><Plus size={18} />New customer</Link>} /><div className="panel"><div className="panel-toolbar"><h2>All customers <span className="count">{data.length}</span></h2><div className="search"><Search size={17} /><input aria-label="Search customers" placeholder="Search customers…" value={search} onChange={e => setSearch(e.target.value)} /></div></div>{items.length ? <div className="table-wrap"><table><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Added</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{items.map(c => <tr key={c.id}><td><Link className="person" href={`/customers/${c.id}`}><span className="avatar light">{c.name.slice(0, 2).toUpperCase()}</span>{c.name}</Link></td><td>{c.email || '—'}</td><td>{c.phone || '—'}</td><td>{date(c.createdAt)}</td><td><Link aria-label={`Open ${c.name}`} href={`/customers/${c.id}`}><ArrowUpRight size={18} /></Link></td></tr>)}</tbody></table></div> : <Empty title={search ? 'No matching customers' : 'Your first customer belongs here'}>{search ? 'Try another name or email.' : 'Add a customer to start a new project.'}</Empty>}</div></>;
}
function CustomerForm() {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const data = Object.fromEntries(new FormData(e.currentTarget)); try { const c = await api<Customer>('/customers', { method: 'POST', body: JSON.stringify(data) }); router.push(`/customers/${c.id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><Link href="/customers" className="back"><ArrowLeft size={16} />Customers</Link><Heading eyebrow="NEW RELATIONSHIP" title="Add a customer" description="Start with the essentials. Keep their projects connected from day one." /><form className="panel form-panel" onSubmit={submit}><ErrorMessage text={error} /><h2>Customer details</h2><label>Name<input name="name" required minLength={2} maxLength={160} placeholder="Person or company name" autoComplete="organization" /></label><div className="form-grid"><label>Email <small>Optional</small><input name="email" type="email" maxLength={254} autoComplete="email" /></label><label>Phone <small>Optional</small><input name="phone" maxLength={60} autoComplete="tel" /></label></div><label>Address <small>Optional</small><textarea name="address" maxLength={500} rows={3} autoComplete="street-address" /></label><div className="form-actions"><Link className="button secondary" href="/customers">Cancel</Link><button className="button" disabled={busy}>{busy ? 'Saving…' : 'Create customer'}<ArrowUpRight size={17} /></button></div></form></>;
}
function CustomerDetail({ id }: { id: string }) { const { data, error } = useResource<{ customer: Customer; projects: Project[] }>(`/customers/${id}`); if (!data) return <Pending error={error} />; const c = data.customer; return <><Link href="/customers" className="back"><ArrowLeft size={16} />Customers</Link><Heading eyebrow="CUSTOMER" title={c.name} description={`In your workspace since ${date(c.createdAt)}`} action={<Link className="button" href={`/projects/new?customer=${id}`}><Plus size={18} />New project</Link>} /><div className="panel contact-grid"><div><span>Email</span><strong>{c.email || 'Not provided'}</strong></div><div><span>Phone</span><strong>{c.phone || 'Not provided'}</strong></div><div><span>Address</span><strong>{c.address || 'Not provided'}</strong></div></div><div className="section-heading"><h2>Projects <span className="count">{data.projects.length}</span></h2></div><ProjectCards items={data.projects} /></>; }
function Projects() { const { data, error } = useResource<Project[]>('/projects'); const [search, setSearch] = useState(''); if (!data) return <Pending error={error} />; return <><Heading eyebrow="FROM IDEA TO INSTALLATION" title="Projects" description="One project. Every version. A complete story." action={<Link className="button" href="/projects/new"><Plus size={18} />New project</Link>} /><div className="section-heading"><h2>All projects <span className="count">{data.length}</span></h2><div className="search"><Search size={17} /><input aria-label="Search projects" placeholder="Search projects…" value={search} onChange={e => setSearch(e.target.value)} /></div></div><ProjectCards items={data.filter(p => `${p.name} ${code(p.id)}`.toLowerCase().includes(search.toLowerCase()))} /></>; }
function ProjectForm() {
  const { data, error: loadError } = useResource<Customer[]>('/customers'); const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [selected, setSelected] = useState('');
  useEffect(() => { setSelected(new URLSearchParams(window.location.search).get('customer') || ''); }, []);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const input = Object.fromEntries(new FormData(e.currentTarget)); try { const p = await api<Project>('/projects', { method: 'POST', body: JSON.stringify(input) }); router.push(`/projects/${p.id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (!data) return <Pending error={loadError} />;
  return <><Link href="/projects" className="back"><ArrowLeft size={16} />Projects</Link><Heading eyebrow="A NEW BEGINNING" title="Create a project" description="Give this job a home before the first design takes shape." />{!data.length ? <Empty title="Add a customer first"><Link className="button" href="/customers/new"><Plus size={17} />Create customer</Link></Empty> : <form className="panel form-panel" onSubmit={submit}><ErrorMessage text={error} /><h2>Project essentials</h2><label>Customer<select name="customerId" value={selected} onChange={e => setSelected(e.target.value)} required><option value="">Select a customer</option>{data.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Project name<input name="name" required minLength={2} maxLength={160} placeholder="For example: Apartment kitchen" /></label><label>Project brief <small>Optional</small><textarea name="description" rows={4} maxLength={2000} placeholder="A short description of the work…" /></label><div className="form-actions"><Link href="/projects" className="button secondary">Cancel</Link><button className="button" disabled={busy}>{busy ? 'Creating…' : 'Create project'}<ArrowUpRight size={17} /></button></div></form>}</>;
}
function ProjectView({ id }: { id: string }) {
  const { data, error, reload } = useResource<ProjectDetail>(`/projects/${id}`); const [tab, setTab] = useState('Overview'); const [showVersion, setShowVersion] = useState(false); const [busy, setBusy] = useState(false); const [mutationError, setMutationError] = useState(''); const [versionId, setVersionId] = useState(''); const [notice, setNotice] = useState(''); const [requestId, setRequestId] = useState('');
  async function version(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const summary = new FormData(e.currentTarget).get('summary'); const key = requestId || crypto.randomUUID(); setRequestId(key); setBusy(true); setMutationError(''); try { await api(`/projects/${id}/versions`, { method: 'POST', body: JSON.stringify({ summary, requestId: key }) }); setShowVersion(false); setRequestId(''); setNotice('Immutable version created. No customer approval or production release has been issued.'); reload(); } catch (e) { setMutationError((e as Error).message); } finally { setBusy(false); } }
  async function upload(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const key = requestId || crypto.randomUUID(); setRequestId(key); setBusy(true); setMutationError(''); try { await api(`/projects/${id}/versions/${versionId || data?.versions[0]?.id}/sources`, { method: 'POST', headers: { 'Idempotency-Key': key }, body: new FormData(form) }); form.reset(); setRequestId(''); setNotice('Original source preserved. Import is pending a verified mapping.'); reload(); } catch (e) { setMutationError((e as Error).message); } finally { setBusy(false); } }
  if (!data) return <Pending error={error} />;
  return <><Link className="back" href="/projects"><ArrowLeft size={16} />Projects</Link><Heading eyebrow={code(id)} title={data.project.name} description={data.customer.name} action={<Badge>Design preparation</Badge>} /><div className="project-summary"><div><span>Customer</span><Link href={`/customers/${data.customer.id}`}>{data.customer.name}<ArrowUpRight size={14} /></Link></div><div><span>Latest version</span><strong>{data.versions.length ? `V${data.versions[0].number}` : 'Not created'}</strong></div><div><span>Customer approval</span><strong>Not requested</strong></div><div><span>Production release</span><strong>Not released</strong></div></div><div className="tabs" role="tablist" aria-label="Project sections">{['Overview', 'Versions', 'Source files', 'Technical model', 'Activity'].map(t => <button role="tab" aria-selected={t === tab} className={t === tab ? 'selected' : ''} key={t} disabled={busy} onClick={() => { setTab(t); setMutationError(''); setRequestId(''); }}>{t}</button>)}</div><ErrorMessage text={mutationError || error} />{notice && <div className="notice" role="status"><CircleCheck size={17} />{notice}<button className="icon-button" aria-label="Dismiss message" onClick={() => setNotice('')}><X size={16} /></button></div>}
  {tab === 'Overview' && <div className="two-columns"><section className="panel padded"><h2>Project brief</h2><p className="preserve">{data.project.description || 'No project brief provided.'}</p><div className="divider" /><span className="eyebrow">NEXT STEPS</span><div className="steps"><button onClick={() => setTab('Versions')}><Layers /><span><strong>{data.versions.length ? 'Review project versions' : 'Create the first version'}</strong><small>Preserve a clear point in the project history.</small></span><ChevronRight /></button><button onClick={() => setTab('Source files')}><FileUp /><span><strong>Keep the original source files</strong><small>Preserve files and review supported CSV exports.</small></span><ChevronRight /></button></div></section><section className="panel padded soft"><LockKeyhole size={25} /><h2>A reliable project history</h2><p>Each version is an immutable snapshot. Later uploads are separate source records linked to that version; they do not rewrite its contents.</p><p>Customer approval and production authorization are separate steps, coming in later increments.</p><span className="small muted">Created {date(data.project.createdAt)}</span></section></div>}
  {tab === 'Versions' && <section className="panel padded"><div className="section-heading"><div><h2>Project versions</h2><p>Preserve decisions without overwriting the past.</p></div><button className="button" disabled={busy} onClick={() => { setShowVersion(!showVersion); setRequestId(''); }}><Plus size={17} />{data.versions.length ? 'New version' : 'Create initial version'}</button></div>{showVersion && <form className="inset-form" onSubmit={version}><label>Version summary<textarea name="summary" required minLength={3} maxLength={2000} rows={3} placeholder="Describe this point in the design…" onChange={() => setRequestId('')} /></label><p className="helper">This creates an immutable design record, not a validated manufacturing dataset.</p><button className="button" disabled={busy}>{busy ? 'Saving…' : 'Save version'}</button></form>}{data.versions.length ? data.versions.map(v => <article className="version" key={v.id}><div className="version-number">V{v.number}</div><div><h3>{v.summary}</h3><p>{date(v.createdAt)} · Not approved · {v.snapshot?.normalizedData ? 'Technical model — needs review' : 'No normalized technical model'}</p></div><span className="lock-label"><LockKeyhole size={14} />Immutable</span></article>) : <Empty title="No versions yet">Create V1 to preserve the first point in this project’s history.</Empty>}</section>}
  {tab === 'Source files' && <section className="panel padded"><h2>PolyBoard source files</h2><p>Preserve the originals, then select a CSV profile to extract data for review. Manufacturing validation remains separate.</p>{data.versions.length ? <form className="upload-area" onSubmit={upload}><FileUp size={30} /><h3>Add an original source file</h3><p>CSV, TXT, DXF, 3DS or PDF · Up to 20 MB per file</p><label>Source version<select value={versionId || data.versions[0].id} onChange={e => { setVersionId(e.target.value); setRequestId(''); }}>{data.versions.map(v => <option key={v.id} value={v.id}>V{v.number} — {v.summary.slice(0, 65)}</option>)}</select></label><label>Choose source file<input type="file" name="file" required accept=".csv,.txt,.dxf,.3ds,.pdf" onChange={() => setRequestId('')} /></label><button className="button" disabled={busy}>{busy ? 'Preserving file…' : 'Upload source'}</button></form> : <Empty title="Create a version first"><button className="button secondary" onClick={() => setTab('Versions')}>Go to versions</button></Empty>}<SourceList items={data.sources} versions={data.versions} onChanged={reload} /></section>}
  {tab === 'Technical model' && <TechnicalModelView projectId={id} sources={data.sources} versions={data.versions} onChanged={reload} />}
  {tab === 'Activity' && <section className="panel padded"><h2>Project activity</h2><p>An append-only record of this project’s history.</p><ol className="timeline">{data.activity.map(a => <li key={a.id}><span className="timeline-dot"><Clock3 size={15} /></span><div><strong>{{ 'project.created': 'Project created', 'version.created': 'Project version created', 'source.preserved': 'Source file preserved', 'import.csv.assessed': 'CSV import assessed', 'technical_model.created': 'Technical model created' }[a.event] || a.event}</strong><p>{a.actor} · {new Date(a.createdAt).toLocaleString('en-GB')}</p>{typeof a.details.name === 'string' && <small>{a.details.name}</small>}{typeof a.details.summary === 'string' && <small>{a.details.summary}</small>}</div></li>)}</ol></section>}</>;
}
function SourceList({ items, versions = [], onChanged }: { items: Source[]; versions?: { id: string; number: number }[]; onChanged?: () => void }) { return items.length ? <div className="source-list">{items.map(s => <article className="source" key={s.id}><Files size={22} /><div className="source-info"><strong>{s.name}</strong><p>{Math.max(1, Math.ceil(s.size / 1024))} KB · {date(s.createdAt)}{versions.find(v => v.id === s.versionId) ? ` · V${versions.find(v => v.id === s.versionId)?.number}` : ''}</p><span className="badge amber">{s.status === 'NEEDS_REVIEW' ? 'Latest import: Needs review' : s.status === 'FAILED' ? 'Latest import: Validation failed' : 'Pending mapping'}</span><p>{s.findings[0]}</p><details><summary>Source integrity</summary><code className="hash">SHA-256: {s.hash}</code></details><CsvImport source={s} onChanged={onChanged} /></div><a className="button secondary small" href={`/api/documents/${s.id}/download`}>Download</a></article>)}</div> : <Empty title="No source files yet">Original uploads will appear here with their integrity hash and import status.</Empty>; }
function Documents() { const { data, error, reload } = useResource<Source[]>('/documents'); if (!data) return <Pending error={error} />; return <><Heading eyebrow="ORIGINALS, PRESERVED" title="Documents" description="Source files across your projects. Private, traceable and unchanged." /><div className="panel padded"><SourceList items={data} onChanged={reload} /></div></>; }
function SettingsView({ identity }: { identity: Identity }) { return <><Heading eyebrow="WORKSPACE" title="Settings" description="Your current access and development environment." /><div className="two-columns"><section className="panel padded"><h2>Your account</h2><p>{identity.name}</p><p>{identity.email}</p><Badge>Local development authentication</Badge><div className="divider" /><h3>Effective capabilities</h3><ul className="capabilities">{identity.capabilities.map(c => <li key={c}><CircleCheck size={16} /><code>{c}</code></li>)}</ul></section><section className="panel padded"><h2>Built to grow incrementally</h2><p>Permission editing, customer access and production authorization are not enabled in this increment.</p><p>Data is stored in PostgreSQL. Original files are kept in private S3-compatible storage.</p><p className="helper">Development data only. This authentication mode is not for a public deployment.</p></section></div></>; }
function ComingLater({ name }: { name: string }) { return <><Heading eyebrow="THE NEXT CHAPTER" title={name} description="Part of the connected manufacturing workflow." /><div className="coming-later"><span className="empty-icon"><Factory size={30} /></span><Badge>Coming later</Badge><h2>A place for {name.toLowerCase()},<br />when the foundation is ready.</h2><p>This module is not active yet. Start by bringing your customers, projects and original design sources together.</p><Link className="button secondary" href="/projects">Go to projects<ArrowUpRight size={17} /></Link></div></>; }

